# exported from PySB model 'model_0'

import numpy as np
from pysb.integrate import Solver
import pylab as pl
import matplotlib.pyplot as plt
from pysb import Model, Monomer, Parameter, Expression, Compartment, Rule, Observable, Initial, MatchOnce, Annotation, ANY, WILD

Model()

Monomer('RAF', ['p1_site', 'ERK', 'state', 'MEK'], {'p1_site': ['p', 'u'], 'state': ['I', 'A']})
Monomer('TGFa', ['EGFR'])
Monomer('IGF1R', ['state', 'IGF1'], {'state': ['A', 'I']})
Monomer('IGF1', ['IGF1R'])
Monomer('PI3K', ['state', 'AKT'], {'state': ['I', 'A']})
Monomer('p70S6K', ['p1_site', 'AKT', 'ERK'], {'p1_site': ['p', 'u']})
Monomer('EGFR', ['p1_site', 'state', 'ERK', 'TGFa'], {'p1_site': ['p', 'u'], 'state': ['A', 'I']})
Monomer('IRS1', ['p1_site', 'AKT', 'ERK'], {'p1_site': ['p', 'u']})
Monomer('MEK', ['p1_site', 'p2_site', 'A_kinase_1', 'A_kinase_2', 'ERK'], {'p1_site': ['p', 'u'], 'A_kinase_1': ['None', '1'], 'A_kinase_2': ['None', '1'], 'p2_site': ['p', 'u']})
Monomer('AKT', ['p1_site', 'p2_site', 'p70S6K', 'IRS1', 'PI3K_1', 'PI3K_2', 'GSK3'], {'p1_site': ['p', 'u'], 'p2_site': ['p', 'u']})
Monomer('GSK3', ['p1_site', 'AKT', 'ERK'], {'p1_site': ['p', 'u']})
Monomer('ERK', ['p1_site', 'RAF', 'p70S6K', 'EGFR', 'IRS1', 'GSK3', 'MEK'], {'p1_site': ['p', 'u']})

Parameter('RAF_p1_auto_dephosphorylation_0_1kc', 1.0)
Parameter('p70S6K_p1_auto_dephosphorylation_0_1kc', 1.0)
Parameter('EGFR_p1_auto_dephosphorylation_0_1kc', 1.0)
Parameter('IRS1_p1_auto_dephosphorylation_0_1kc', 1.0)
Parameter('MEK_p2_auto_dephosphorylation_0_1kc', 1.0)
Parameter('MEK_p2_auto_dephosphorylation_1_1kc', 1.0)
Parameter('AKT_p2_auto_dephosphorylation_0_1kc', 1.0)
Parameter('AKT_p2_auto_dephosphorylation_1_1kc', 1.0)
Parameter('GSK3_p1_auto_dephosphorylation_0_1kc', 1.0)
Parameter('ERK_p1_auto_dephosphorylation_0_1kc', 1.0)
Parameter('ERK_p1_p1_phosphorylation_RAF_0_2kf', 1.0)
Parameter('ERK_p1_p1_phosphorylation_RAF_0_1kr', 1.0)
Parameter('ERK_p1_p1_phosphorylation_RAF_1_1kc', 1.0)
Parameter('EGFR_A_u_activation_RAF_0_2kc', 1.0)
Parameter('IGF1R_A_activation_RAF_0_2kc', 1.0)
Parameter('IGF1_ligand_receptor_binding_IGF1R_0_2kf', 1.0)
Parameter('IGF1_ligand_receptor_binding_IGF1R_0_1kr', 1.0)
Parameter('EGFR_A_u_activation_PI3K_0_2kc', 1.0)
Parameter('IGF1R_A_activation_PI3K_0_2kc', 1.0)
Parameter('AKT_p2_p1_phosphorylation_p70S6K_0_2kf', 1.0)
Parameter('AKT_p2_p1_phosphorylation_p70S6K_0_1kr', 1.0)
Parameter('AKT_p2_p1_phosphorylation_p70S6K_1_1kc', 1.0)
Parameter('ERK_p1_p1_phosphorylation_p70S6K_0_2kf', 1.0)
Parameter('ERK_p1_p1_phosphorylation_p70S6K_0_1kr', 1.0)
Parameter('ERK_p1_p1_phosphorylation_p70S6K_1_1kc', 1.0)
Parameter('ERK_p1_p1_phosphorylation_EGFR_0_2kf', 1.0)
Parameter('ERK_p1_p1_phosphorylation_EGFR_0_1kr', 1.0)
Parameter('ERK_p1_p1_phosphorylation_EGFR_1_1kc', 1.0)
Parameter('TGFa_ligand_receptor_binding_EGFR_0_2kf', 1.0)
Parameter('TGFa_ligand_receptor_binding_EGFR_0_1kr', 1.0)
Parameter('AKT_p2_p1_phosphorylation_IRS1_0_2kf', 1.0)
Parameter('AKT_p2_p1_phosphorylation_IRS1_0_1kr', 1.0)
Parameter('AKT_p2_p1_phosphorylation_IRS1_1_1kc', 1.0)
Parameter('ERK_p1_p1_phosphorylation_IRS1_0_2kf', 1.0)
Parameter('ERK_p1_p1_phosphorylation_IRS1_0_1kr', 1.0)
Parameter('ERK_p1_p1_phosphorylation_IRS1_1_1kc', 1.0)
Parameter('RAF_A_u_p2_phosphorylation_MEK_0_2kf', 1.0)
Parameter('RAF_A_u_p2_phosphorylation_MEK_0_1kr', 1.0)
Parameter('RAF_A_u_p2_phosphorylation_MEK_1_1kc', 1.0)
Parameter('RAF_A_u_p2_phosphorylation_MEK_2_2kf', 1.0)
Parameter('RAF_A_u_p2_phosphorylation_MEK_2_1kr', 1.0)
Parameter('RAF_A_u_p2_phosphorylation_MEK_3_1kc', 1.0)
Parameter('PI3K_A_p2_phosphorylation_AKT_0_2kf', 1.0)
Parameter('PI3K_A_p2_phosphorylation_AKT_0_1kr', 1.0)
Parameter('PI3K_A_p2_phosphorylation_AKT_1_1kc', 1.0)
Parameter('PI3K_A_p2_phosphorylation_AKT_2_2kf', 1.0)
Parameter('PI3K_A_p2_phosphorylation_AKT_2_1kr', 1.0)
Parameter('PI3K_A_p2_phosphorylation_AKT_3_1kc', 1.0)
Parameter('AKT_p2_p1_phosphorylation_GSK3_0_2kf', 1.0)
Parameter('AKT_p2_p1_phosphorylation_GSK3_0_1kr', 1.0)
Parameter('AKT_p2_p1_phosphorylation_GSK3_1_1kc', 1.0)
Parameter('ERK_p1_p1_phosphorylation_GSK3_0_2kf', 1.0)
Parameter('ERK_p1_p1_phosphorylation_GSK3_0_1kr', 1.0)
Parameter('ERK_p1_p1_phosphorylation_GSK3_1_1kc', 1.0)
Parameter('MEK_p2_p1_phosphorylation_ERK_0_2kf', 1.0)
Parameter('MEK_p2_p1_phosphorylation_ERK_0_1kr', 1.0)
Parameter('MEK_p2_p1_phosphorylation_ERK_1_1kc', 1.0)
Parameter('RAF_0_0', 0.0)
Parameter('RAF_1_0', 0.0)
Parameter('RAF_2_0', 0.0)
Parameter('RAF_3_0', 0.0)
Parameter('TGFa_0_0', 0.0)
Parameter('IGF1R_0_0', 0.0)
Parameter('IGF1R_1_0', 0.0)
Parameter('IGF1_0_0', 0.0)
Parameter('PI3K_0_0', 0.0)
Parameter('PI3K_1_0', 0.0)
Parameter('p70S6K_0_0', 0.0)
Parameter('p70S6K_1_0', 0.0)
Parameter('EGFR_0_0', 0.0)
Parameter('EGFR_1_0', 0.0)
Parameter('EGFR_2_0', 0.0)
Parameter('EGFR_3_0', 0.0)
Parameter('IRS1_0_0', 0.0)
Parameter('IRS1_1_0', 0.0)
Parameter('MEK_0_0', 0.0)
Parameter('MEK_1_0', 0.0)
Parameter('MEK_2_0', 0.0)
Parameter('MEK_3_0', 0.0)
Parameter('MEK_4_0', 0.0)
Parameter('MEK_5_0', 0.0)
Parameter('MEK_6_0', 0.0)
Parameter('MEK_7_0', 0.0)
Parameter('MEK_8_0', 0.0)
Parameter('MEK_9_0', 0.0)
Parameter('MEK_10_0', 0.0)
Parameter('MEK_11_0', 0.0)
Parameter('MEK_12_0', 0.0)
Parameter('MEK_13_0', 0.0)
Parameter('MEK_14_0', 0.0)
Parameter('MEK_15_0', 0.0)
Parameter('AKT_0_0', 0.0)
Parameter('AKT_1_0', 0.0)
Parameter('AKT_2_0', 0.0)
Parameter('AKT_3_0', 0.0)
Parameter('GSK3_0_0', 0.0)
Parameter('GSK3_1_0', 0.0)
Parameter('ERK_0_0', 0.0)
Parameter('ERK_1_0', 0.0)

Observable('RAF_0_obs', RAF(p1_site='p', ERK=None, state='I', MEK=None))
Observable('RAF_1_obs', RAF(p1_site='p', ERK=None, state='I', MEK=ANY))
Observable('RAF_2_obs', RAF(p1_site='p', ERK=None, state='A', MEK=None))
Observable('RAF_3_obs', RAF(p1_site='p', ERK=None, state='A', MEK=ANY))
Observable('RAF_4_obs', RAF(p1_site='p', ERK=ANY, state='I', MEK=None))
Observable('RAF_5_obs', RAF(p1_site='p', ERK=ANY, state='I', MEK=ANY))
Observable('RAF_6_obs', RAF(p1_site='p', ERK=ANY, state='A', MEK=None))
Observable('RAF_7_obs', RAF(p1_site='p', ERK=ANY, state='A', MEK=ANY))
Observable('RAF_8_obs', RAF(p1_site='u', ERK=None, state='I', MEK=None))
Observable('RAF_9_obs', RAF(p1_site='u', ERK=None, state='I', MEK=ANY))
Observable('RAF_10_obs', RAF(p1_site='u', ERK=None, state='A', MEK=None))
Observable('RAF_11_obs', RAF(p1_site='u', ERK=None, state='A', MEK=ANY))
Observable('RAF_12_obs', RAF(p1_site='u', ERK=ANY, state='I', MEK=None))
Observable('RAF_13_obs', RAF(p1_site='u', ERK=ANY, state='I', MEK=ANY))
Observable('RAF_14_obs', RAF(p1_site='u', ERK=ANY, state='A', MEK=None))
Observable('RAF_15_obs', RAF(p1_site='u', ERK=ANY, state='A', MEK=ANY))
Observable('TGFa_0_obs', TGFa(EGFR=None))
Observable('TGFa_1_obs', TGFa(EGFR=ANY))
Observable('IGF1R_0_obs', IGF1R(state='A', IGF1=None))
Observable('IGF1R_1_obs', IGF1R(state='A', IGF1=ANY))
Observable('IGF1R_2_obs', IGF1R(state='I', IGF1=None))
Observable('IGF1R_3_obs', IGF1R(state='I', IGF1=ANY))
Observable('IGF1_0_obs', IGF1(IGF1R=None))
Observable('IGF1_1_obs', IGF1(IGF1R=ANY))
Observable('PI3K_0_obs', PI3K(state='I', AKT=None))
Observable('PI3K_1_obs', PI3K(state='I', AKT=ANY))
Observable('PI3K_2_obs', PI3K(state='A', AKT=None))
Observable('PI3K_3_obs', PI3K(state='A', AKT=ANY))
Observable('p70S6K_0_obs', p70S6K(p1_site='p', AKT=None, ERK=None))
Observable('p70S6K_1_obs', p70S6K(p1_site='p', AKT=None, ERK=ANY))
Observable('p70S6K_2_obs', p70S6K(p1_site='p', AKT=ANY, ERK=None))
Observable('p70S6K_3_obs', p70S6K(p1_site='p', AKT=ANY, ERK=ANY))
Observable('p70S6K_4_obs', p70S6K(p1_site='u', AKT=None, ERK=None))
Observable('p70S6K_5_obs', p70S6K(p1_site='u', AKT=None, ERK=ANY))
Observable('p70S6K_6_obs', p70S6K(p1_site='u', AKT=ANY, ERK=None))
Observable('p70S6K_7_obs', p70S6K(p1_site='u', AKT=ANY, ERK=ANY))
Observable('EGFR_0_obs', EGFR(p1_site='p', state='A', ERK=None, TGFa=None))
Observable('EGFR_1_obs', EGFR(p1_site='p', state='A', ERK=None, TGFa=ANY))
Observable('EGFR_2_obs', EGFR(p1_site='p', state='A', ERK=ANY, TGFa=None))
Observable('EGFR_3_obs', EGFR(p1_site='p', state='A', ERK=ANY, TGFa=ANY))
Observable('EGFR_4_obs', EGFR(p1_site='p', state='I', ERK=None, TGFa=None))
Observable('EGFR_5_obs', EGFR(p1_site='p', state='I', ERK=None, TGFa=ANY))
Observable('EGFR_6_obs', EGFR(p1_site='p', state='I', ERK=ANY, TGFa=None))
Observable('EGFR_7_obs', EGFR(p1_site='p', state='I', ERK=ANY, TGFa=ANY))
Observable('EGFR_8_obs', EGFR(p1_site='u', state='A', ERK=None, TGFa=None))
Observable('EGFR_9_obs', EGFR(p1_site='u', state='A', ERK=None, TGFa=ANY))
Observable('EGFR_10_obs', EGFR(p1_site='u', state='A', ERK=ANY, TGFa=None))
Observable('EGFR_11_obs', EGFR(p1_site='u', state='A', ERK=ANY, TGFa=ANY))
Observable('EGFR_12_obs', EGFR(p1_site='u', state='I', ERK=None, TGFa=None))
Observable('EGFR_13_obs', EGFR(p1_site='u', state='I', ERK=None, TGFa=ANY))
Observable('EGFR_14_obs', EGFR(p1_site='u', state='I', ERK=ANY, TGFa=None))
Observable('EGFR_15_obs', EGFR(p1_site='u', state='I', ERK=ANY, TGFa=ANY))
Observable('IRS1_0_obs', IRS1(p1_site='p', AKT=None, ERK=None))
Observable('IRS1_1_obs', IRS1(p1_site='p', AKT=None, ERK=ANY))
Observable('IRS1_2_obs', IRS1(p1_site='p', AKT=ANY, ERK=None))
Observable('IRS1_3_obs', IRS1(p1_site='p', AKT=ANY, ERK=ANY))
Observable('IRS1_4_obs', IRS1(p1_site='u', AKT=None, ERK=None))
Observable('IRS1_5_obs', IRS1(p1_site='u', AKT=None, ERK=ANY))
Observable('IRS1_6_obs', IRS1(p1_site='u', AKT=ANY, ERK=None))
Observable('IRS1_7_obs', IRS1(p1_site='u', AKT=ANY, ERK=ANY))
Observable('MEK_0_obs', MEK(p1_site='p', p2_site='p', A_kinase_1='None', A_kinase_2='None', ERK=None))
Observable('MEK_1_obs', MEK(p1_site='p', p2_site='p', A_kinase_1='None', A_kinase_2='None', ERK=ANY))
Observable('MEK_2_obs', MEK(p1_site='p', p2_site='p', A_kinase_1='None', A_kinase_2='1', ERK=None))
Observable('MEK_3_obs', MEK(p1_site='p', p2_site='p', A_kinase_1='None', A_kinase_2='1', ERK=ANY))
Observable('MEK_4_obs', MEK(p1_site='p', p2_site='p', A_kinase_1='1', A_kinase_2='None', ERK=None))
Observable('MEK_5_obs', MEK(p1_site='p', p2_site='p', A_kinase_1='1', A_kinase_2='None', ERK=ANY))
Observable('MEK_6_obs', MEK(p1_site='p', p2_site='p', A_kinase_1='1', A_kinase_2='1', ERK=None))
Observable('MEK_7_obs', MEK(p1_site='p', p2_site='p', A_kinase_1='1', A_kinase_2='1', ERK=ANY))
Observable('MEK_8_obs', MEK(p1_site='p', p2_site='u', A_kinase_1='None', A_kinase_2='None', ERK=None))
Observable('MEK_9_obs', MEK(p1_site='p', p2_site='u', A_kinase_1='None', A_kinase_2='None', ERK=ANY))
Observable('MEK_10_obs', MEK(p1_site='p', p2_site='u', A_kinase_1='None', A_kinase_2='1', ERK=None))
Observable('MEK_11_obs', MEK(p1_site='p', p2_site='u', A_kinase_1='None', A_kinase_2='1', ERK=ANY))
Observable('MEK_12_obs', MEK(p1_site='p', p2_site='u', A_kinase_1='1', A_kinase_2='None', ERK=None))
Observable('MEK_13_obs', MEK(p1_site='p', p2_site='u', A_kinase_1='1', A_kinase_2='None', ERK=ANY))
Observable('MEK_14_obs', MEK(p1_site='p', p2_site='u', A_kinase_1='1', A_kinase_2='1', ERK=None))
Observable('MEK_15_obs', MEK(p1_site='p', p2_site='u', A_kinase_1='1', A_kinase_2='1', ERK=ANY))
Observable('MEK_16_obs', MEK(p1_site='u', p2_site='p', A_kinase_1='None', A_kinase_2='None', ERK=None))
Observable('MEK_17_obs', MEK(p1_site='u', p2_site='p', A_kinase_1='None', A_kinase_2='None', ERK=ANY))
Observable('MEK_18_obs', MEK(p1_site='u', p2_site='p', A_kinase_1='None', A_kinase_2='1', ERK=None))
Observable('MEK_19_obs', MEK(p1_site='u', p2_site='p', A_kinase_1='None', A_kinase_2='1', ERK=ANY))
Observable('MEK_20_obs', MEK(p1_site='u', p2_site='p', A_kinase_1='1', A_kinase_2='None', ERK=None))
Observable('MEK_21_obs', MEK(p1_site='u', p2_site='p', A_kinase_1='1', A_kinase_2='None', ERK=ANY))
Observable('MEK_22_obs', MEK(p1_site='u', p2_site='p', A_kinase_1='1', A_kinase_2='1', ERK=None))
Observable('MEK_23_obs', MEK(p1_site='u', p2_site='p', A_kinase_1='1', A_kinase_2='1', ERK=ANY))
Observable('MEK_24_obs', MEK(p1_site='u', p2_site='u', A_kinase_1='None', A_kinase_2='None', ERK=None))
Observable('MEK_25_obs', MEK(p1_site='u', p2_site='u', A_kinase_1='None', A_kinase_2='None', ERK=ANY))
Observable('MEK_26_obs', MEK(p1_site='u', p2_site='u', A_kinase_1='None', A_kinase_2='1', ERK=None))
Observable('MEK_27_obs', MEK(p1_site='u', p2_site='u', A_kinase_1='None', A_kinase_2='1', ERK=ANY))
Observable('MEK_28_obs', MEK(p1_site='u', p2_site='u', A_kinase_1='1', A_kinase_2='None', ERK=None))
Observable('MEK_29_obs', MEK(p1_site='u', p2_site='u', A_kinase_1='1', A_kinase_2='None', ERK=ANY))
Observable('MEK_30_obs', MEK(p1_site='u', p2_site='u', A_kinase_1='1', A_kinase_2='1', ERK=None))
Observable('MEK_31_obs', MEK(p1_site='u', p2_site='u', A_kinase_1='1', A_kinase_2='1', ERK=ANY))
Observable('AKT_0_obs', AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None))
Observable('AKT_1_obs', AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=ANY))
Observable('AKT_2_obs', AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=ANY, GSK3=None))
Observable('AKT_3_obs', AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_4_obs', AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=None, PI3K_1=ANY, PI3K_2=None, GSK3=None))
Observable('AKT_5_obs', AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=None, PI3K_1=ANY, PI3K_2=None, GSK3=ANY))
Observable('AKT_6_obs', AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=None, PI3K_1=ANY, PI3K_2=ANY, GSK3=None))
Observable('AKT_7_obs', AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=None, PI3K_1=ANY, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_8_obs', AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=ANY, PI3K_1=None, PI3K_2=None, GSK3=None))
Observable('AKT_9_obs', AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=ANY, PI3K_1=None, PI3K_2=None, GSK3=ANY))
Observable('AKT_10_obs', AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=ANY, PI3K_1=None, PI3K_2=ANY, GSK3=None))
Observable('AKT_11_obs', AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=ANY, PI3K_1=None, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_12_obs', AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=ANY, PI3K_1=ANY, PI3K_2=None, GSK3=None))
Observable('AKT_13_obs', AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=ANY, PI3K_1=ANY, PI3K_2=None, GSK3=ANY))
Observable('AKT_14_obs', AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=ANY, PI3K_1=ANY, PI3K_2=ANY, GSK3=None))
Observable('AKT_15_obs', AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=ANY, PI3K_1=ANY, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_16_obs', AKT(p1_site='p', p2_site='p', p70S6K=ANY, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None))
Observable('AKT_17_obs', AKT(p1_site='p', p2_site='p', p70S6K=ANY, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=ANY))
Observable('AKT_18_obs', AKT(p1_site='p', p2_site='p', p70S6K=ANY, IRS1=None, PI3K_1=None, PI3K_2=ANY, GSK3=None))
Observable('AKT_19_obs', AKT(p1_site='p', p2_site='p', p70S6K=ANY, IRS1=None, PI3K_1=None, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_20_obs', AKT(p1_site='p', p2_site='p', p70S6K=ANY, IRS1=None, PI3K_1=ANY, PI3K_2=None, GSK3=None))
Observable('AKT_21_obs', AKT(p1_site='p', p2_site='p', p70S6K=ANY, IRS1=None, PI3K_1=ANY, PI3K_2=None, GSK3=ANY))
Observable('AKT_22_obs', AKT(p1_site='p', p2_site='p', p70S6K=ANY, IRS1=None, PI3K_1=ANY, PI3K_2=ANY, GSK3=None))
Observable('AKT_23_obs', AKT(p1_site='p', p2_site='p', p70S6K=ANY, IRS1=None, PI3K_1=ANY, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_24_obs', AKT(p1_site='p', p2_site='p', p70S6K=ANY, IRS1=ANY, PI3K_1=None, PI3K_2=None, GSK3=None))
Observable('AKT_25_obs', AKT(p1_site='p', p2_site='p', p70S6K=ANY, IRS1=ANY, PI3K_1=None, PI3K_2=None, GSK3=ANY))
Observable('AKT_26_obs', AKT(p1_site='p', p2_site='p', p70S6K=ANY, IRS1=ANY, PI3K_1=None, PI3K_2=ANY, GSK3=None))
Observable('AKT_27_obs', AKT(p1_site='p', p2_site='p', p70S6K=ANY, IRS1=ANY, PI3K_1=None, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_28_obs', AKT(p1_site='p', p2_site='p', p70S6K=ANY, IRS1=ANY, PI3K_1=ANY, PI3K_2=None, GSK3=None))
Observable('AKT_29_obs', AKT(p1_site='p', p2_site='p', p70S6K=ANY, IRS1=ANY, PI3K_1=ANY, PI3K_2=None, GSK3=ANY))
Observable('AKT_30_obs', AKT(p1_site='p', p2_site='p', p70S6K=ANY, IRS1=ANY, PI3K_1=ANY, PI3K_2=ANY, GSK3=None))
Observable('AKT_31_obs', AKT(p1_site='p', p2_site='p', p70S6K=ANY, IRS1=ANY, PI3K_1=ANY, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_32_obs', AKT(p1_site='p', p2_site='u', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None))
Observable('AKT_33_obs', AKT(p1_site='p', p2_site='u', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=ANY))
Observable('AKT_34_obs', AKT(p1_site='p', p2_site='u', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=ANY, GSK3=None))
Observable('AKT_35_obs', AKT(p1_site='p', p2_site='u', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_36_obs', AKT(p1_site='p', p2_site='u', p70S6K=None, IRS1=None, PI3K_1=ANY, PI3K_2=None, GSK3=None))
Observable('AKT_37_obs', AKT(p1_site='p', p2_site='u', p70S6K=None, IRS1=None, PI3K_1=ANY, PI3K_2=None, GSK3=ANY))
Observable('AKT_38_obs', AKT(p1_site='p', p2_site='u', p70S6K=None, IRS1=None, PI3K_1=ANY, PI3K_2=ANY, GSK3=None))
Observable('AKT_39_obs', AKT(p1_site='p', p2_site='u', p70S6K=None, IRS1=None, PI3K_1=ANY, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_40_obs', AKT(p1_site='p', p2_site='u', p70S6K=None, IRS1=ANY, PI3K_1=None, PI3K_2=None, GSK3=None))
Observable('AKT_41_obs', AKT(p1_site='p', p2_site='u', p70S6K=None, IRS1=ANY, PI3K_1=None, PI3K_2=None, GSK3=ANY))
Observable('AKT_42_obs', AKT(p1_site='p', p2_site='u', p70S6K=None, IRS1=ANY, PI3K_1=None, PI3K_2=ANY, GSK3=None))
Observable('AKT_43_obs', AKT(p1_site='p', p2_site='u', p70S6K=None, IRS1=ANY, PI3K_1=None, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_44_obs', AKT(p1_site='p', p2_site='u', p70S6K=None, IRS1=ANY, PI3K_1=ANY, PI3K_2=None, GSK3=None))
Observable('AKT_45_obs', AKT(p1_site='p', p2_site='u', p70S6K=None, IRS1=ANY, PI3K_1=ANY, PI3K_2=None, GSK3=ANY))
Observable('AKT_46_obs', AKT(p1_site='p', p2_site='u', p70S6K=None, IRS1=ANY, PI3K_1=ANY, PI3K_2=ANY, GSK3=None))
Observable('AKT_47_obs', AKT(p1_site='p', p2_site='u', p70S6K=None, IRS1=ANY, PI3K_1=ANY, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_48_obs', AKT(p1_site='p', p2_site='u', p70S6K=ANY, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None))
Observable('AKT_49_obs', AKT(p1_site='p', p2_site='u', p70S6K=ANY, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=ANY))
Observable('AKT_50_obs', AKT(p1_site='p', p2_site='u', p70S6K=ANY, IRS1=None, PI3K_1=None, PI3K_2=ANY, GSK3=None))
Observable('AKT_51_obs', AKT(p1_site='p', p2_site='u', p70S6K=ANY, IRS1=None, PI3K_1=None, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_52_obs', AKT(p1_site='p', p2_site='u', p70S6K=ANY, IRS1=None, PI3K_1=ANY, PI3K_2=None, GSK3=None))
Observable('AKT_53_obs', AKT(p1_site='p', p2_site='u', p70S6K=ANY, IRS1=None, PI3K_1=ANY, PI3K_2=None, GSK3=ANY))
Observable('AKT_54_obs', AKT(p1_site='p', p2_site='u', p70S6K=ANY, IRS1=None, PI3K_1=ANY, PI3K_2=ANY, GSK3=None))
Observable('AKT_55_obs', AKT(p1_site='p', p2_site='u', p70S6K=ANY, IRS1=None, PI3K_1=ANY, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_56_obs', AKT(p1_site='p', p2_site='u', p70S6K=ANY, IRS1=ANY, PI3K_1=None, PI3K_2=None, GSK3=None))
Observable('AKT_57_obs', AKT(p1_site='p', p2_site='u', p70S6K=ANY, IRS1=ANY, PI3K_1=None, PI3K_2=None, GSK3=ANY))
Observable('AKT_58_obs', AKT(p1_site='p', p2_site='u', p70S6K=ANY, IRS1=ANY, PI3K_1=None, PI3K_2=ANY, GSK3=None))
Observable('AKT_59_obs', AKT(p1_site='p', p2_site='u', p70S6K=ANY, IRS1=ANY, PI3K_1=None, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_60_obs', AKT(p1_site='p', p2_site='u', p70S6K=ANY, IRS1=ANY, PI3K_1=ANY, PI3K_2=None, GSK3=None))
Observable('AKT_61_obs', AKT(p1_site='p', p2_site='u', p70S6K=ANY, IRS1=ANY, PI3K_1=ANY, PI3K_2=None, GSK3=ANY))
Observable('AKT_62_obs', AKT(p1_site='p', p2_site='u', p70S6K=ANY, IRS1=ANY, PI3K_1=ANY, PI3K_2=ANY, GSK3=None))
Observable('AKT_63_obs', AKT(p1_site='p', p2_site='u', p70S6K=ANY, IRS1=ANY, PI3K_1=ANY, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_64_obs', AKT(p1_site='u', p2_site='p', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None))
Observable('AKT_65_obs', AKT(p1_site='u', p2_site='p', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=ANY))
Observable('AKT_66_obs', AKT(p1_site='u', p2_site='p', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=ANY, GSK3=None))
Observable('AKT_67_obs', AKT(p1_site='u', p2_site='p', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_68_obs', AKT(p1_site='u', p2_site='p', p70S6K=None, IRS1=None, PI3K_1=ANY, PI3K_2=None, GSK3=None))
Observable('AKT_69_obs', AKT(p1_site='u', p2_site='p', p70S6K=None, IRS1=None, PI3K_1=ANY, PI3K_2=None, GSK3=ANY))
Observable('AKT_70_obs', AKT(p1_site='u', p2_site='p', p70S6K=None, IRS1=None, PI3K_1=ANY, PI3K_2=ANY, GSK3=None))
Observable('AKT_71_obs', AKT(p1_site='u', p2_site='p', p70S6K=None, IRS1=None, PI3K_1=ANY, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_72_obs', AKT(p1_site='u', p2_site='p', p70S6K=None, IRS1=ANY, PI3K_1=None, PI3K_2=None, GSK3=None))
Observable('AKT_73_obs', AKT(p1_site='u', p2_site='p', p70S6K=None, IRS1=ANY, PI3K_1=None, PI3K_2=None, GSK3=ANY))
Observable('AKT_74_obs', AKT(p1_site='u', p2_site='p', p70S6K=None, IRS1=ANY, PI3K_1=None, PI3K_2=ANY, GSK3=None))
Observable('AKT_75_obs', AKT(p1_site='u', p2_site='p', p70S6K=None, IRS1=ANY, PI3K_1=None, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_76_obs', AKT(p1_site='u', p2_site='p', p70S6K=None, IRS1=ANY, PI3K_1=ANY, PI3K_2=None, GSK3=None))
Observable('AKT_77_obs', AKT(p1_site='u', p2_site='p', p70S6K=None, IRS1=ANY, PI3K_1=ANY, PI3K_2=None, GSK3=ANY))
Observable('AKT_78_obs', AKT(p1_site='u', p2_site='p', p70S6K=None, IRS1=ANY, PI3K_1=ANY, PI3K_2=ANY, GSK3=None))
Observable('AKT_79_obs', AKT(p1_site='u', p2_site='p', p70S6K=None, IRS1=ANY, PI3K_1=ANY, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_80_obs', AKT(p1_site='u', p2_site='p', p70S6K=ANY, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None))
Observable('AKT_81_obs', AKT(p1_site='u', p2_site='p', p70S6K=ANY, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=ANY))
Observable('AKT_82_obs', AKT(p1_site='u', p2_site='p', p70S6K=ANY, IRS1=None, PI3K_1=None, PI3K_2=ANY, GSK3=None))
Observable('AKT_83_obs', AKT(p1_site='u', p2_site='p', p70S6K=ANY, IRS1=None, PI3K_1=None, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_84_obs', AKT(p1_site='u', p2_site='p', p70S6K=ANY, IRS1=None, PI3K_1=ANY, PI3K_2=None, GSK3=None))
Observable('AKT_85_obs', AKT(p1_site='u', p2_site='p', p70S6K=ANY, IRS1=None, PI3K_1=ANY, PI3K_2=None, GSK3=ANY))
Observable('AKT_86_obs', AKT(p1_site='u', p2_site='p', p70S6K=ANY, IRS1=None, PI3K_1=ANY, PI3K_2=ANY, GSK3=None))
Observable('AKT_87_obs', AKT(p1_site='u', p2_site='p', p70S6K=ANY, IRS1=None, PI3K_1=ANY, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_88_obs', AKT(p1_site='u', p2_site='p', p70S6K=ANY, IRS1=ANY, PI3K_1=None, PI3K_2=None, GSK3=None))
Observable('AKT_89_obs', AKT(p1_site='u', p2_site='p', p70S6K=ANY, IRS1=ANY, PI3K_1=None, PI3K_2=None, GSK3=ANY))
Observable('AKT_90_obs', AKT(p1_site='u', p2_site='p', p70S6K=ANY, IRS1=ANY, PI3K_1=None, PI3K_2=ANY, GSK3=None))
Observable('AKT_91_obs', AKT(p1_site='u', p2_site='p', p70S6K=ANY, IRS1=ANY, PI3K_1=None, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_92_obs', AKT(p1_site='u', p2_site='p', p70S6K=ANY, IRS1=ANY, PI3K_1=ANY, PI3K_2=None, GSK3=None))
Observable('AKT_93_obs', AKT(p1_site='u', p2_site='p', p70S6K=ANY, IRS1=ANY, PI3K_1=ANY, PI3K_2=None, GSK3=ANY))
Observable('AKT_94_obs', AKT(p1_site='u', p2_site='p', p70S6K=ANY, IRS1=ANY, PI3K_1=ANY, PI3K_2=ANY, GSK3=None))
Observable('AKT_95_obs', AKT(p1_site='u', p2_site='p', p70S6K=ANY, IRS1=ANY, PI3K_1=ANY, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_96_obs', AKT(p1_site='u', p2_site='u', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None))
Observable('AKT_97_obs', AKT(p1_site='u', p2_site='u', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=ANY))
Observable('AKT_98_obs', AKT(p1_site='u', p2_site='u', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=ANY, GSK3=None))
Observable('AKT_99_obs', AKT(p1_site='u', p2_site='u', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_100_obs', AKT(p1_site='u', p2_site='u', p70S6K=None, IRS1=None, PI3K_1=ANY, PI3K_2=None, GSK3=None))
Observable('AKT_101_obs', AKT(p1_site='u', p2_site='u', p70S6K=None, IRS1=None, PI3K_1=ANY, PI3K_2=None, GSK3=ANY))
Observable('AKT_102_obs', AKT(p1_site='u', p2_site='u', p70S6K=None, IRS1=None, PI3K_1=ANY, PI3K_2=ANY, GSK3=None))
Observable('AKT_103_obs', AKT(p1_site='u', p2_site='u', p70S6K=None, IRS1=None, PI3K_1=ANY, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_104_obs', AKT(p1_site='u', p2_site='u', p70S6K=None, IRS1=ANY, PI3K_1=None, PI3K_2=None, GSK3=None))
Observable('AKT_105_obs', AKT(p1_site='u', p2_site='u', p70S6K=None, IRS1=ANY, PI3K_1=None, PI3K_2=None, GSK3=ANY))
Observable('AKT_106_obs', AKT(p1_site='u', p2_site='u', p70S6K=None, IRS1=ANY, PI3K_1=None, PI3K_2=ANY, GSK3=None))
Observable('AKT_107_obs', AKT(p1_site='u', p2_site='u', p70S6K=None, IRS1=ANY, PI3K_1=None, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_108_obs', AKT(p1_site='u', p2_site='u', p70S6K=None, IRS1=ANY, PI3K_1=ANY, PI3K_2=None, GSK3=None))
Observable('AKT_109_obs', AKT(p1_site='u', p2_site='u', p70S6K=None, IRS1=ANY, PI3K_1=ANY, PI3K_2=None, GSK3=ANY))
Observable('AKT_110_obs', AKT(p1_site='u', p2_site='u', p70S6K=None, IRS1=ANY, PI3K_1=ANY, PI3K_2=ANY, GSK3=None))
Observable('AKT_111_obs', AKT(p1_site='u', p2_site='u', p70S6K=None, IRS1=ANY, PI3K_1=ANY, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_112_obs', AKT(p1_site='u', p2_site='u', p70S6K=ANY, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None))
Observable('AKT_113_obs', AKT(p1_site='u', p2_site='u', p70S6K=ANY, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=ANY))
Observable('AKT_114_obs', AKT(p1_site='u', p2_site='u', p70S6K=ANY, IRS1=None, PI3K_1=None, PI3K_2=ANY, GSK3=None))
Observable('AKT_115_obs', AKT(p1_site='u', p2_site='u', p70S6K=ANY, IRS1=None, PI3K_1=None, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_116_obs', AKT(p1_site='u', p2_site='u', p70S6K=ANY, IRS1=None, PI3K_1=ANY, PI3K_2=None, GSK3=None))
Observable('AKT_117_obs', AKT(p1_site='u', p2_site='u', p70S6K=ANY, IRS1=None, PI3K_1=ANY, PI3K_2=None, GSK3=ANY))
Observable('AKT_118_obs', AKT(p1_site='u', p2_site='u', p70S6K=ANY, IRS1=None, PI3K_1=ANY, PI3K_2=ANY, GSK3=None))
Observable('AKT_119_obs', AKT(p1_site='u', p2_site='u', p70S6K=ANY, IRS1=None, PI3K_1=ANY, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_120_obs', AKT(p1_site='u', p2_site='u', p70S6K=ANY, IRS1=ANY, PI3K_1=None, PI3K_2=None, GSK3=None))
Observable('AKT_121_obs', AKT(p1_site='u', p2_site='u', p70S6K=ANY, IRS1=ANY, PI3K_1=None, PI3K_2=None, GSK3=ANY))
Observable('AKT_122_obs', AKT(p1_site='u', p2_site='u', p70S6K=ANY, IRS1=ANY, PI3K_1=None, PI3K_2=ANY, GSK3=None))
Observable('AKT_123_obs', AKT(p1_site='u', p2_site='u', p70S6K=ANY, IRS1=ANY, PI3K_1=None, PI3K_2=ANY, GSK3=ANY))
Observable('AKT_124_obs', AKT(p1_site='u', p2_site='u', p70S6K=ANY, IRS1=ANY, PI3K_1=ANY, PI3K_2=None, GSK3=None))
Observable('AKT_125_obs', AKT(p1_site='u', p2_site='u', p70S6K=ANY, IRS1=ANY, PI3K_1=ANY, PI3K_2=None, GSK3=ANY))
Observable('AKT_126_obs', AKT(p1_site='u', p2_site='u', p70S6K=ANY, IRS1=ANY, PI3K_1=ANY, PI3K_2=ANY, GSK3=None))
Observable('AKT_127_obs', AKT(p1_site='u', p2_site='u', p70S6K=ANY, IRS1=ANY, PI3K_1=ANY, PI3K_2=ANY, GSK3=ANY))
Observable('GSK3_0_obs', GSK3(p1_site='p', AKT=None, ERK=None))
Observable('GSK3_1_obs', GSK3(p1_site='p', AKT=None, ERK=ANY))
Observable('GSK3_2_obs', GSK3(p1_site='p', AKT=ANY, ERK=None))
Observable('GSK3_3_obs', GSK3(p1_site='p', AKT=ANY, ERK=ANY))
Observable('GSK3_4_obs', GSK3(p1_site='u', AKT=None, ERK=None))
Observable('GSK3_5_obs', GSK3(p1_site='u', AKT=None, ERK=ANY))
Observable('GSK3_6_obs', GSK3(p1_site='u', AKT=ANY, ERK=None))
Observable('GSK3_7_obs', GSK3(p1_site='u', AKT=ANY, ERK=ANY))
Observable('ERK_0_obs', ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=None))
Observable('ERK_1_obs', ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=ANY))
Observable('ERK_2_obs', ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK=None))
Observable('ERK_3_obs', ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK=ANY))
Observable('ERK_4_obs', ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK=None))
Observable('ERK_5_obs', ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK=ANY))
Observable('ERK_6_obs', ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK=None))
Observable('ERK_7_obs', ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK=ANY))
Observable('ERK_8_obs', ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK=None))
Observable('ERK_9_obs', ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK=ANY))
Observable('ERK_10_obs', ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK=None))
Observable('ERK_11_obs', ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK=ANY))
Observable('ERK_12_obs', ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK=None))
Observable('ERK_13_obs', ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK=ANY))
Observable('ERK_14_obs', ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK=None))
Observable('ERK_15_obs', ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK=ANY))
Observable('ERK_16_obs', ERK(p1_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK=None))
Observable('ERK_17_obs', ERK(p1_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK=ANY))
Observable('ERK_18_obs', ERK(p1_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK=None))
Observable('ERK_19_obs', ERK(p1_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK=ANY))
Observable('ERK_20_obs', ERK(p1_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK=None))
Observable('ERK_21_obs', ERK(p1_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK=ANY))
Observable('ERK_22_obs', ERK(p1_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK=None))
Observable('ERK_23_obs', ERK(p1_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK=ANY))
Observable('ERK_24_obs', ERK(p1_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK=None))
Observable('ERK_25_obs', ERK(p1_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK=ANY))
Observable('ERK_26_obs', ERK(p1_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK=None))
Observable('ERK_27_obs', ERK(p1_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK=ANY))
Observable('ERK_28_obs', ERK(p1_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK=None))
Observable('ERK_29_obs', ERK(p1_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK=ANY))
Observable('ERK_30_obs', ERK(p1_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK=None))
Observable('ERK_31_obs', ERK(p1_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK=ANY))
Observable('ERK_32_obs', ERK(p1_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=None))
Observable('ERK_33_obs', ERK(p1_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=ANY))
Observable('ERK_34_obs', ERK(p1_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK=None))
Observable('ERK_35_obs', ERK(p1_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK=ANY))
Observable('ERK_36_obs', ERK(p1_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK=None))
Observable('ERK_37_obs', ERK(p1_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK=ANY))
Observable('ERK_38_obs', ERK(p1_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK=None))
Observable('ERK_39_obs', ERK(p1_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK=ANY))
Observable('ERK_40_obs', ERK(p1_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK=None))
Observable('ERK_41_obs', ERK(p1_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK=ANY))
Observable('ERK_42_obs', ERK(p1_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK=None))
Observable('ERK_43_obs', ERK(p1_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK=ANY))
Observable('ERK_44_obs', ERK(p1_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK=None))
Observable('ERK_45_obs', ERK(p1_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK=ANY))
Observable('ERK_46_obs', ERK(p1_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK=None))
Observable('ERK_47_obs', ERK(p1_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK=ANY))
Observable('ERK_48_obs', ERK(p1_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK=None))
Observable('ERK_49_obs', ERK(p1_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK=ANY))
Observable('ERK_50_obs', ERK(p1_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK=None))
Observable('ERK_51_obs', ERK(p1_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK=ANY))
Observable('ERK_52_obs', ERK(p1_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK=None))
Observable('ERK_53_obs', ERK(p1_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK=ANY))
Observable('ERK_54_obs', ERK(p1_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK=None))
Observable('ERK_55_obs', ERK(p1_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK=ANY))
Observable('ERK_56_obs', ERK(p1_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK=None))
Observable('ERK_57_obs', ERK(p1_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK=ANY))
Observable('ERK_58_obs', ERK(p1_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK=None))
Observable('ERK_59_obs', ERK(p1_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK=ANY))
Observable('ERK_60_obs', ERK(p1_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK=None))
Observable('ERK_61_obs', ERK(p1_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK=ANY))
Observable('ERK_62_obs', ERK(p1_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK=None))
Observable('ERK_63_obs', ERK(p1_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK=ANY))
Observable('ERK_64_obs', ERK(p1_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=None))
Observable('ERK_65_obs', ERK(p1_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=ANY))
Observable('ERK_66_obs', ERK(p1_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK=None))
Observable('ERK_67_obs', ERK(p1_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK=ANY))
Observable('ERK_68_obs', ERK(p1_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK=None))
Observable('ERK_69_obs', ERK(p1_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK=ANY))
Observable('ERK_70_obs', ERK(p1_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK=None))
Observable('ERK_71_obs', ERK(p1_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK=ANY))
Observable('ERK_72_obs', ERK(p1_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK=None))
Observable('ERK_73_obs', ERK(p1_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK=ANY))
Observable('ERK_74_obs', ERK(p1_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK=None))
Observable('ERK_75_obs', ERK(p1_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK=ANY))
Observable('ERK_76_obs', ERK(p1_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK=None))
Observable('ERK_77_obs', ERK(p1_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK=ANY))
Observable('ERK_78_obs', ERK(p1_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK=None))
Observable('ERK_79_obs', ERK(p1_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK=ANY))
Observable('ERK_80_obs', ERK(p1_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK=None))
Observable('ERK_81_obs', ERK(p1_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK=ANY))
Observable('ERK_82_obs', ERK(p1_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK=None))
Observable('ERK_83_obs', ERK(p1_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK=ANY))
Observable('ERK_84_obs', ERK(p1_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK=None))
Observable('ERK_85_obs', ERK(p1_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK=ANY))
Observable('ERK_86_obs', ERK(p1_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK=None))
Observable('ERK_87_obs', ERK(p1_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK=ANY))
Observable('ERK_88_obs', ERK(p1_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK=None))
Observable('ERK_89_obs', ERK(p1_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK=ANY))
Observable('ERK_90_obs', ERK(p1_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK=None))
Observable('ERK_91_obs', ERK(p1_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK=ANY))
Observable('ERK_92_obs', ERK(p1_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK=None))
Observable('ERK_93_obs', ERK(p1_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK=ANY))
Observable('ERK_94_obs', ERK(p1_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK=None))
Observable('ERK_95_obs', ERK(p1_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK=ANY))
Observable('ERK_96_obs', ERK(p1_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=None))
Observable('ERK_97_obs', ERK(p1_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=ANY))
Observable('ERK_98_obs', ERK(p1_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK=None))
Observable('ERK_99_obs', ERK(p1_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK=ANY))
Observable('ERK_100_obs', ERK(p1_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK=None))
Observable('ERK_101_obs', ERK(p1_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK=ANY))
Observable('ERK_102_obs', ERK(p1_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK=None))
Observable('ERK_103_obs', ERK(p1_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK=ANY))
Observable('ERK_104_obs', ERK(p1_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK=None))
Observable('ERK_105_obs', ERK(p1_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK=ANY))
Observable('ERK_106_obs', ERK(p1_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK=None))
Observable('ERK_107_obs', ERK(p1_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK=ANY))
Observable('ERK_108_obs', ERK(p1_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK=None))
Observable('ERK_109_obs', ERK(p1_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK=ANY))
Observable('ERK_110_obs', ERK(p1_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK=None))
Observable('ERK_111_obs', ERK(p1_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK=ANY))
Observable('ERK_112_obs', ERK(p1_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK=None))
Observable('ERK_113_obs', ERK(p1_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK=ANY))
Observable('ERK_114_obs', ERK(p1_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK=None))
Observable('ERK_115_obs', ERK(p1_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK=ANY))
Observable('ERK_116_obs', ERK(p1_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK=None))
Observable('ERK_117_obs', ERK(p1_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK=ANY))
Observable('ERK_118_obs', ERK(p1_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK=None))
Observable('ERK_119_obs', ERK(p1_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK=ANY))
Observable('ERK_120_obs', ERK(p1_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK=None))
Observable('ERK_121_obs', ERK(p1_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK=ANY))
Observable('ERK_122_obs', ERK(p1_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK=None))
Observable('ERK_123_obs', ERK(p1_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK=ANY))
Observable('ERK_124_obs', ERK(p1_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK=None))
Observable('ERK_125_obs', ERK(p1_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK=ANY))
Observable('ERK_126_obs', ERK(p1_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK=None))
Observable('ERK_127_obs', ERK(p1_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK=ANY))

Rule('RAF_p1_auto_dephosphorylation_0', RAF(p1_site='p', ERK=None, MEK=None) >> RAF(p1_site='u', ERK=None, MEK=None), RAF_p1_auto_dephosphorylation_0_1kc)
Rule('p70S6K_p1_auto_dephosphorylation_0', p70S6K(p1_site='p', AKT=None, ERK=None) >> p70S6K(p1_site='u', AKT=None, ERK=None), p70S6K_p1_auto_dephosphorylation_0_1kc)
Rule('EGFR_p1_auto_dephosphorylation_0', EGFR(p1_site='p', ERK=None, TGFa=None) >> EGFR(p1_site='u', ERK=None, TGFa=None), EGFR_p1_auto_dephosphorylation_0_1kc)
Rule('IRS1_p1_auto_dephosphorylation_0', IRS1(p1_site='p', AKT=None, ERK=None) >> IRS1(p1_site='u', AKT=None, ERK=None), IRS1_p1_auto_dephosphorylation_0_1kc)
Rule('MEK_p2_auto_dephosphorylation_0', MEK(p1_site='p', ERK=None) >> MEK(p1_site='u', ERK=None), MEK_p2_auto_dephosphorylation_0_1kc)
Rule('MEK_p2_auto_dephosphorylation_1', MEK(p2_site='p', ERK=None) >> MEK(p2_site='u', ERK=None), MEK_p2_auto_dephosphorylation_1_1kc)
Rule('AKT_p2_auto_dephosphorylation_0', AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None) >> AKT(p1_site='u', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None), AKT_p2_auto_dephosphorylation_0_1kc)
Rule('AKT_p2_auto_dephosphorylation_1', AKT(p2_site='p', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None) >> AKT(p2_site='u', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None), AKT_p2_auto_dephosphorylation_1_1kc)
Rule('GSK3_p1_auto_dephosphorylation_0', GSK3(p1_site='p', AKT=None, ERK=None) >> GSK3(p1_site='u', AKT=None, ERK=None), GSK3_p1_auto_dephosphorylation_0_1kc)
Rule('ERK_p1_auto_dephosphorylation_0', ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=None) >> ERK(p1_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=None), ERK_p1_auto_dephosphorylation_0_1kc)
Rule('ERK_p1_p1_phosphorylation_RAF_0', ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=None) + RAF(p1_site='u', ERK=None, MEK=None) <> ERK(p1_site='p', RAF=1, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=None) % RAF(p1_site='u', ERK=1, MEK=None), ERK_p1_p1_phosphorylation_RAF_0_2kf, ERK_p1_p1_phosphorylation_RAF_0_1kr)
Rule('ERK_p1_p1_phosphorylation_RAF_1', ERK(p1_site='p', RAF=1, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=None) % RAF(p1_site='u', ERK=1, MEK=None) >> ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=None) + RAF(p1_site='p', ERK=None, MEK=None), ERK_p1_p1_phosphorylation_RAF_1_1kc)
Rule('EGFR_A_u_activation_RAF_0', EGFR(p1_site='u', state='A') + RAF(state='I') >> EGFR(p1_site='u', state='A') + RAF(state='A'), EGFR_A_u_activation_RAF_0_2kc)
Rule('IGF1R_A_activation_RAF_0', IGF1R(state='A') + RAF(state='I') >> IGF1R(state='A') + RAF(state='A'), IGF1R_A_activation_RAF_0_2kc)
Rule('IGF1_ligand_receptor_binding_IGF1R_0', IGF1(IGF1R=None) + IGF1R(state='I', IGF1=None) <> IGF1(IGF1R=1) % IGF1R(state='A', IGF1=1), IGF1_ligand_receptor_binding_IGF1R_0_2kf, IGF1_ligand_receptor_binding_IGF1R_0_1kr)
Rule('EGFR_A_u_activation_PI3K_0', EGFR(p1_site='u', state='A') + PI3K(state='I') >> EGFR(p1_site='u', state='A') + PI3K(state='A'), EGFR_A_u_activation_PI3K_0_2kc)
Rule('IGF1R_A_activation_PI3K_0', IGF1R(state='A') + PI3K(state='I') >> IGF1R(state='A') + PI3K(state='A'), IGF1R_A_activation_PI3K_0_2kc)
Rule('AKT_p2_p1_phosphorylation_p70S6K_0', AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None) + p70S6K(p1_site='u', AKT=None, ERK=None) <> AKT(p1_site='p', p2_site='p', p70S6K=1, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None) % p70S6K(p1_site='u', AKT=1, ERK=None), AKT_p2_p1_phosphorylation_p70S6K_0_2kf, AKT_p2_p1_phosphorylation_p70S6K_0_1kr)
Rule('AKT_p2_p1_phosphorylation_p70S6K_1', AKT(p1_site='p', p2_site='p', p70S6K=1, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None) % p70S6K(p1_site='u', AKT=1, ERK=None) >> AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None) + p70S6K(p1_site='p', AKT=None, ERK=None), AKT_p2_p1_phosphorylation_p70S6K_1_1kc)
Rule('ERK_p1_p1_phosphorylation_p70S6K_0', ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=None) + p70S6K(p1_site='u', AKT=None, ERK=None) <> ERK(p1_site='p', RAF=None, p70S6K=1, EGFR=None, IRS1=None, GSK3=None, MEK=None) % p70S6K(p1_site='u', AKT=None, ERK=1), ERK_p1_p1_phosphorylation_p70S6K_0_2kf, ERK_p1_p1_phosphorylation_p70S6K_0_1kr)
Rule('ERK_p1_p1_phosphorylation_p70S6K_1', ERK(p1_site='p', RAF=None, p70S6K=1, EGFR=None, IRS1=None, GSK3=None, MEK=None) % p70S6K(p1_site='u', AKT=None, ERK=1) >> ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=None) + p70S6K(p1_site='p', AKT=None, ERK=None), ERK_p1_p1_phosphorylation_p70S6K_1_1kc)
Rule('ERK_p1_p1_phosphorylation_EGFR_0', ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=None) + EGFR(p1_site='u', ERK=None, TGFa=None) <> ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=1, IRS1=None, GSK3=None, MEK=None) % EGFR(p1_site='u', ERK=1, TGFa=None), ERK_p1_p1_phosphorylation_EGFR_0_2kf, ERK_p1_p1_phosphorylation_EGFR_0_1kr)
Rule('ERK_p1_p1_phosphorylation_EGFR_1', ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=1, IRS1=None, GSK3=None, MEK=None) % EGFR(p1_site='u', ERK=1, TGFa=None) >> ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=None) + EGFR(p1_site='p', ERK=None, TGFa=None), ERK_p1_p1_phosphorylation_EGFR_1_1kc)
Rule('TGFa_ligand_receptor_binding_EGFR_0', TGFa(EGFR=None) + EGFR(state='I', ERK=None, TGFa=None) <> TGFa(EGFR=1) % EGFR(state='A', ERK=None, TGFa=1), TGFa_ligand_receptor_binding_EGFR_0_2kf, TGFa_ligand_receptor_binding_EGFR_0_1kr)
Rule('AKT_p2_p1_phosphorylation_IRS1_0', AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None) + IRS1(p1_site='u', AKT=None, ERK=None) <> AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=1, PI3K_1=None, PI3K_2=None, GSK3=None) % IRS1(p1_site='u', AKT=1, ERK=None), AKT_p2_p1_phosphorylation_IRS1_0_2kf, AKT_p2_p1_phosphorylation_IRS1_0_1kr)
Rule('AKT_p2_p1_phosphorylation_IRS1_1', AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=1, PI3K_1=None, PI3K_2=None, GSK3=None) % IRS1(p1_site='u', AKT=1, ERK=None) >> AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None) + IRS1(p1_site='p', AKT=None, ERK=None), AKT_p2_p1_phosphorylation_IRS1_1_1kc)
Rule('ERK_p1_p1_phosphorylation_IRS1_0', ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=None) + IRS1(p1_site='u', AKT=None, ERK=None) <> ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=1, GSK3=None, MEK=None) % IRS1(p1_site='u', AKT=None, ERK=1), ERK_p1_p1_phosphorylation_IRS1_0_2kf, ERK_p1_p1_phosphorylation_IRS1_0_1kr)
Rule('ERK_p1_p1_phosphorylation_IRS1_1', ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=1, GSK3=None, MEK=None) % IRS1(p1_site='u', AKT=None, ERK=1) >> ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=None) + IRS1(p1_site='p', AKT=None, ERK=None), ERK_p1_p1_phosphorylation_IRS1_1_1kc)
Rule('RAF_A_u_p2_phosphorylation_MEK_0', RAF(p1_site='u', ERK=None, state='A', MEK=None) + MEK(p1_site='u', A_kinase_1=None, ERK=None) <> RAF(p1_site='u', ERK=None, state='A', MEK=1) % MEK(p1_site='u', A_kinase_1='1', ERK=None), RAF_A_u_p2_phosphorylation_MEK_0_2kf, RAF_A_u_p2_phosphorylation_MEK_0_1kr)
Rule('RAF_A_u_p2_phosphorylation_MEK_1', RAF(p1_site='u', ERK=None, state='A', MEK=1) % MEK(p1_site='u', A_kinase_1='1', ERK=None) >> RAF(p1_site='u', ERK=None, state='A', MEK=None) + MEK(p1_site='p', A_kinase_1=None, ERK=None), RAF_A_u_p2_phosphorylation_MEK_1_1kc)
Rule('RAF_A_u_p2_phosphorylation_MEK_2', RAF(p1_site='u', ERK=None, state='A', MEK=None) + MEK(p2_site='u', A_kinase_2=None, ERK=None) <> RAF(p1_site='u', ERK=None, state='A', MEK=1) % MEK(p2_site='u', A_kinase_2='1', ERK=None), RAF_A_u_p2_phosphorylation_MEK_2_2kf, RAF_A_u_p2_phosphorylation_MEK_2_1kr)
Rule('RAF_A_u_p2_phosphorylation_MEK_3', RAF(p1_site='u', ERK=None, state='A', MEK=1) % MEK(p2_site='u', A_kinase_2='1', ERK=None) >> RAF(p1_site='u', ERK=None, state='A', MEK=None) + MEK(p2_site='p', A_kinase_2=None, ERK=None), RAF_A_u_p2_phosphorylation_MEK_3_1kc)
Rule('PI3K_A_p2_phosphorylation_AKT_0', PI3K(state='A', AKT=None) + AKT(p1_site='u', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None) <> PI3K(state='A', AKT=1) % AKT(p1_site='u', p70S6K=None, IRS1=None, PI3K_1=1, PI3K_2=None, GSK3=None), PI3K_A_p2_phosphorylation_AKT_0_2kf, PI3K_A_p2_phosphorylation_AKT_0_1kr)
Rule('PI3K_A_p2_phosphorylation_AKT_1', PI3K(state='A', AKT=1) % AKT(p1_site='u', p70S6K=None, IRS1=None, PI3K_1=1, PI3K_2=None, GSK3=None) >> PI3K(state='A', AKT=None) + AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None), PI3K_A_p2_phosphorylation_AKT_1_1kc)
Rule('PI3K_A_p2_phosphorylation_AKT_2', PI3K(state='A', AKT=None) + AKT(p2_site='u', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None) <> PI3K(state='A', AKT=1) % AKT(p2_site='u', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=1, GSK3=None), PI3K_A_p2_phosphorylation_AKT_2_2kf, PI3K_A_p2_phosphorylation_AKT_2_1kr)
Rule('PI3K_A_p2_phosphorylation_AKT_3', PI3K(state='A', AKT=1) % AKT(p2_site='u', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=1, GSK3=None) >> PI3K(state='A', AKT=None) + AKT(p2_site='p', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None), PI3K_A_p2_phosphorylation_AKT_3_1kc)
Rule('AKT_p2_p1_phosphorylation_GSK3_0', AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None) + GSK3(p1_site='u', AKT=None, ERK=None) <> AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=1) % GSK3(p1_site='u', AKT=1, ERK=None), AKT_p2_p1_phosphorylation_GSK3_0_2kf, AKT_p2_p1_phosphorylation_GSK3_0_1kr)
Rule('AKT_p2_p1_phosphorylation_GSK3_1', AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=1) % GSK3(p1_site='u', AKT=1, ERK=None) >> AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None) + GSK3(p1_site='p', AKT=None, ERK=None), AKT_p2_p1_phosphorylation_GSK3_1_1kc)
Rule('ERK_p1_p1_phosphorylation_GSK3_0', ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=None) + GSK3(p1_site='u', AKT=None, ERK=None) <> ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=1, MEK=None) % GSK3(p1_site='u', AKT=None, ERK=1), ERK_p1_p1_phosphorylation_GSK3_0_2kf, ERK_p1_p1_phosphorylation_GSK3_0_1kr)
Rule('ERK_p1_p1_phosphorylation_GSK3_1', ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=1, MEK=None) % GSK3(p1_site='u', AKT=None, ERK=1) >> ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=None) + GSK3(p1_site='p', AKT=None, ERK=None), ERK_p1_p1_phosphorylation_GSK3_1_1kc)
Rule('MEK_p2_p1_phosphorylation_ERK_0', MEK(p1_site='p', p2_site='p', ERK=None) + ERK(p1_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=None) <> MEK(p1_site='p', p2_site='p', ERK=1) % ERK(p1_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=1), MEK_p2_p1_phosphorylation_ERK_0_2kf, MEK_p2_p1_phosphorylation_ERK_0_1kr)
Rule('MEK_p2_p1_phosphorylation_ERK_1', MEK(p1_site='p', p2_site='p', ERK=1) % ERK(p1_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=1) >> MEK(p1_site='p', p2_site='p', ERK=None) + ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=None), MEK_p2_p1_phosphorylation_ERK_1_1kc)

Initial(RAF(p1_site='p', ERK=None, state='I', MEK=None), RAF_0_0)
Initial(RAF(p1_site='p', ERK=None, state='A', MEK=None), RAF_1_0)
Initial(RAF(p1_site='u', ERK=None, state='I', MEK=None), RAF_2_0)
Initial(RAF(p1_site='u', ERK=None, state='A', MEK=None), RAF_3_0)
Initial(TGFa(EGFR=None), TGFa_0_0)
Initial(IGF1R(state='A', IGF1=None), IGF1R_0_0)
Initial(IGF1R(state='I', IGF1=None), IGF1R_1_0)
Initial(IGF1(IGF1R=None), IGF1_0_0)
Initial(PI3K(state='I', AKT=None), PI3K_0_0)
Initial(PI3K(state='A', AKT=None), PI3K_1_0)
Initial(p70S6K(p1_site='p', AKT=None, ERK=None), p70S6K_0_0)
Initial(p70S6K(p1_site='u', AKT=None, ERK=None), p70S6K_1_0)
Initial(EGFR(p1_site='p', state='A', ERK=None, TGFa=None), EGFR_0_0)
Initial(EGFR(p1_site='p', state='I', ERK=None, TGFa=None), EGFR_1_0)
Initial(EGFR(p1_site='u', state='A', ERK=None, TGFa=None), EGFR_2_0)
Initial(EGFR(p1_site='u', state='I', ERK=None, TGFa=None), EGFR_3_0)
Initial(IRS1(p1_site='p', AKT=None, ERK=None), IRS1_0_0)
Initial(IRS1(p1_site='u', AKT=None, ERK=None), IRS1_1_0)
Initial(MEK(p1_site='p', p2_site='p', A_kinase_1='None', A_kinase_2='None', ERK=None), MEK_0_0)
Initial(MEK(p1_site='p', p2_site='p', A_kinase_1='None', A_kinase_2='1', ERK=None), MEK_1_0)
Initial(MEK(p1_site='p', p2_site='p', A_kinase_1='1', A_kinase_2='None', ERK=None), MEK_2_0)
Initial(MEK(p1_site='p', p2_site='p', A_kinase_1='1', A_kinase_2='1', ERK=None), MEK_3_0)
Initial(MEK(p1_site='p', p2_site='u', A_kinase_1='None', A_kinase_2='None', ERK=None), MEK_4_0)
Initial(MEK(p1_site='p', p2_site='u', A_kinase_1='None', A_kinase_2='1', ERK=None), MEK_5_0)
Initial(MEK(p1_site='p', p2_site='u', A_kinase_1='1', A_kinase_2='None', ERK=None), MEK_6_0)
Initial(MEK(p1_site='p', p2_site='u', A_kinase_1='1', A_kinase_2='1', ERK=None), MEK_7_0)
Initial(MEK(p1_site='u', p2_site='p', A_kinase_1='None', A_kinase_2='None', ERK=None), MEK_8_0)
Initial(MEK(p1_site='u', p2_site='p', A_kinase_1='None', A_kinase_2='1', ERK=None), MEK_9_0)
Initial(MEK(p1_site='u', p2_site='p', A_kinase_1='1', A_kinase_2='None', ERK=None), MEK_10_0)
Initial(MEK(p1_site='u', p2_site='p', A_kinase_1='1', A_kinase_2='1', ERK=None), MEK_11_0)
Initial(MEK(p1_site='u', p2_site='u', A_kinase_1='None', A_kinase_2='None', ERK=None), MEK_12_0)
Initial(MEK(p1_site='u', p2_site='u', A_kinase_1='None', A_kinase_2='1', ERK=None), MEK_13_0)
Initial(MEK(p1_site='u', p2_site='u', A_kinase_1='1', A_kinase_2='None', ERK=None), MEK_14_0)
Initial(MEK(p1_site='u', p2_site='u', A_kinase_1='1', A_kinase_2='1', ERK=None), MEK_15_0)
Initial(AKT(p1_site='p', p2_site='p', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None), AKT_0_0)
Initial(AKT(p1_site='p', p2_site='u', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None), AKT_1_0)
Initial(AKT(p1_site='u', p2_site='p', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None), AKT_2_0)
Initial(AKT(p1_site='u', p2_site='u', p70S6K=None, IRS1=None, PI3K_1=None, PI3K_2=None, GSK3=None), AKT_3_0)
Initial(GSK3(p1_site='p', AKT=None, ERK=None), GSK3_0_0)
Initial(GSK3(p1_site='u', AKT=None, ERK=None), GSK3_1_0)
Initial(ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=None), ERK_0_0)
Initial(ERK(p1_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK=None), ERK_1_0)

