# exported from PySB model 'model_0'

import numpy as np
from pysb.integrate import Solver
import pylab as pl
import matplotlib.pyplot as plt
from pysb import Model, Monomer, Parameter, Expression, Compartment, Rule, Observable, Initial, MatchOnce, Annotation, ANY, WILD

Model()

Monomer('RAF', ['p1_site', 'ERK', 'state', 'MEK'], {'p1_site': ['p', 'u'], 'state': ['I', 'A']})
Monomer('TGFa', ['EGFR'])
Monomer('IGF1R', ['state', 'IGF1'], {'state': ['A', 'I']})
Monomer('IGF1', ['IGF1R'])
Monomer('PI3K', ['state', 'AKT'], {'state': ['I', 'A']})
Monomer('p70S6K', ['p1_site', 'ERK', 'AKT'], {'p1_site': ['p', 'u']})
Monomer('EGFR', ['p1_site', 'state', 'ERK', 'TGFa'], {'p1_site': ['p', 'u'], 'state': ['A', 'I']})
Monomer('IRS1', ['p1_site', 'ERK', 'AKT'], {'p1_site': ['p', 'u']})
Monomer('MEK', ['p1_site', 'p2_site', 'A_kinase_1', 'A_kinase_2', 'ERK'], {'p1_site': ['p', 'u'], 'A_kinase_1': ['None', '1'], 'A_kinase_2': ['None', '1'], 'p2_site': ['p', 'u']})
Monomer('AKT', ['p1_site', 'p70S6K', 'IRS1', 'PI3K', 'GSK3'], {'p1_site': ['p', 'u']})
Monomer('GSK3', ['p1_site', 'ERK', 'AKT'], {'p1_site': ['p', 'u']})
Monomer('ERK', ['p1_site', 'p2_site', 'RAF', 'p70S6K', 'EGFR', 'IRS1', 'GSK3', 'MEK_1', 'MEK_2'], {'p1_site': ['p', 'u'], 'p2_site': ['p', 'u']})

Parameter('RAF_p1_auto_dephosphorylation_0_1kc', 1.0)
Parameter('p70S6K_p1_auto_dephosphorylation_0_1kc', 1.0)
Parameter('EGFR_p1_auto_dephosphorylation_0_1kc', 1.0)
Parameter('IRS1_p1_auto_dephosphorylation_0_1kc', 1.0)
Parameter('MEK_p2_auto_dephosphorylation_0_1kc', 1.0)
Parameter('MEK_p2_auto_dephosphorylation_1_1kc', 1.0)
Parameter('AKT_p1_auto_dephosphorylation_0_1kc', 1.0)
Parameter('GSK3_p1_auto_dephosphorylation_0_1kc', 1.0)
Parameter('ERK_p2_auto_dephosphorylation_0_1kc', 1.0)
Parameter('ERK_p2_auto_dephosphorylation_1_1kc', 1.0)
Parameter('ERK_p2_p1_phosphorylation_RAF_0_2kf', 1.0)
Parameter('ERK_p2_p1_phosphorylation_RAF_0_1kr', 1.0)
Parameter('ERK_p2_p1_phosphorylation_RAF_1_1kc', 1.0)
Parameter('EGFR_A_u_activation_RAF_0_2kc', 1.0)
Parameter('IGF1R_A_activation_RAF_0_2kc', 1.0)
Parameter('IGF1_ligand_receptor_binding_IGF1R_0_2kf', 1.0)
Parameter('IGF1_ligand_receptor_binding_IGF1R_0_1kr', 1.0)
Parameter('EGFR_A_u_activation_PI3K_0_2kc', 1.0)
Parameter('IGF1R_A_activation_PI3K_0_2kc', 1.0)
Parameter('ERK_p2_p1_phosphorylation_p70S6K_0_2kf', 1.0)
Parameter('ERK_p2_p1_phosphorylation_p70S6K_0_1kr', 1.0)
Parameter('ERK_p2_p1_phosphorylation_p70S6K_1_1kc', 1.0)
Parameter('AKT_p1_p1_phosphorylation_p70S6K_0_2kf', 1.0)
Parameter('AKT_p1_p1_phosphorylation_p70S6K_0_1kr', 1.0)
Parameter('AKT_p1_p1_phosphorylation_p70S6K_1_1kc', 1.0)
Parameter('ERK_p2_p1_phosphorylation_EGFR_0_2kf', 1.0)
Parameter('ERK_p2_p1_phosphorylation_EGFR_0_1kr', 1.0)
Parameter('ERK_p2_p1_phosphorylation_EGFR_1_1kc', 1.0)
Parameter('TGFa_ligand_receptor_binding_EGFR_0_2kf', 1.0)
Parameter('TGFa_ligand_receptor_binding_EGFR_0_1kr', 1.0)
Parameter('ERK_p2_p1_phosphorylation_IRS1_0_2kf', 1.0)
Parameter('ERK_p2_p1_phosphorylation_IRS1_0_1kr', 1.0)
Parameter('ERK_p2_p1_phosphorylation_IRS1_1_1kc', 1.0)
Parameter('AKT_p1_p1_phosphorylation_IRS1_0_2kf', 1.0)
Parameter('AKT_p1_p1_phosphorylation_IRS1_0_1kr', 1.0)
Parameter('AKT_p1_p1_phosphorylation_IRS1_1_1kc', 1.0)
Parameter('RAF_A_u_p2_phosphorylation_MEK_0_2kf', 1.0)
Parameter('RAF_A_u_p2_phosphorylation_MEK_0_1kr', 1.0)
Parameter('RAF_A_u_p2_phosphorylation_MEK_1_1kc', 1.0)
Parameter('RAF_A_u_p2_phosphorylation_MEK_2_2kf', 1.0)
Parameter('RAF_A_u_p2_phosphorylation_MEK_2_1kr', 1.0)
Parameter('RAF_A_u_p2_phosphorylation_MEK_3_1kc', 1.0)
Parameter('PI3K_A_p1_phosphorylation_AKT_0_2kf', 1.0)
Parameter('PI3K_A_p1_phosphorylation_AKT_0_1kr', 1.0)
Parameter('PI3K_A_p1_phosphorylation_AKT_1_1kc', 1.0)
Parameter('ERK_p2_p1_phosphorylation_GSK3_0_2kf', 1.0)
Parameter('ERK_p2_p1_phosphorylation_GSK3_0_1kr', 1.0)
Parameter('ERK_p2_p1_phosphorylation_GSK3_1_1kc', 1.0)
Parameter('AKT_p1_p1_phosphorylation_GSK3_0_2kf', 1.0)
Parameter('AKT_p1_p1_phosphorylation_GSK3_0_1kr', 1.0)
Parameter('AKT_p1_p1_phosphorylation_GSK3_1_1kc', 1.0)
Parameter('MEK_p2_p2_phosphorylation_ERK_0_2kf', 1.0)
Parameter('MEK_p2_p2_phosphorylation_ERK_0_1kr', 1.0)
Parameter('MEK_p2_p2_phosphorylation_ERK_1_1kc', 1.0)
Parameter('MEK_p2_p2_phosphorylation_ERK_2_2kf', 1.0)
Parameter('MEK_p2_p2_phosphorylation_ERK_2_1kr', 1.0)
Parameter('MEK_p2_p2_phosphorylation_ERK_3_1kc', 1.0)
Parameter('RAF_0_0', 0.0)
Parameter('RAF_1_0', 0.0)
Parameter('RAF_2_0', 0.0)
Parameter('RAF_3_0', 0.0)
Parameter('TGFa_0_0', 0.0)
Parameter('IGF1R_0_0', 0.0)
Parameter('IGF1R_1_0', 0.0)
Parameter('IGF1_0_0', 0.0)
Parameter('PI3K_0_0', 0.0)
Parameter('PI3K_1_0', 0.0)
Parameter('p70S6K_0_0', 0.0)
Parameter('p70S6K_1_0', 0.0)
Parameter('EGFR_0_0', 0.0)
Parameter('EGFR_1_0', 0.0)
Parameter('EGFR_2_0', 0.0)
Parameter('EGFR_3_0', 0.0)
Parameter('IRS1_0_0', 0.0)
Parameter('IRS1_1_0', 0.0)
Parameter('MEK_0_0', 0.0)
Parameter('MEK_1_0', 0.0)
Parameter('MEK_2_0', 0.0)
Parameter('MEK_3_0', 0.0)
Parameter('MEK_4_0', 0.0)
Parameter('MEK_5_0', 0.0)
Parameter('MEK_6_0', 0.0)
Parameter('MEK_7_0', 0.0)
Parameter('MEK_8_0', 0.0)
Parameter('MEK_9_0', 0.0)
Parameter('MEK_10_0', 0.0)
Parameter('MEK_11_0', 0.0)
Parameter('MEK_12_0', 0.0)
Parameter('MEK_13_0', 0.0)
Parameter('MEK_14_0', 0.0)
Parameter('MEK_15_0', 0.0)
Parameter('AKT_0_0', 0.0)
Parameter('AKT_1_0', 0.0)
Parameter('GSK3_0_0', 0.0)
Parameter('GSK3_1_0', 0.0)
Parameter('ERK_0_0', 0.0)
Parameter('ERK_1_0', 0.0)
Parameter('ERK_2_0', 0.0)
Parameter('ERK_3_0', 0.0)

Observable('RAF_0_obs', RAF(p1_site='p', ERK=None, state='I', MEK=None))
Observable('RAF_1_obs', RAF(p1_site='p', ERK=None, state='I', MEK=ANY))
Observable('RAF_2_obs', RAF(p1_site='p', ERK=None, state='A', MEK=None))
Observable('RAF_3_obs', RAF(p1_site='p', ERK=None, state='A', MEK=ANY))
Observable('RAF_4_obs', RAF(p1_site='p', ERK=ANY, state='I', MEK=None))
Observable('RAF_5_obs', RAF(p1_site='p', ERK=ANY, state='I', MEK=ANY))
Observable('RAF_6_obs', RAF(p1_site='p', ERK=ANY, state='A', MEK=None))
Observable('RAF_7_obs', RAF(p1_site='p', ERK=ANY, state='A', MEK=ANY))
Observable('RAF_8_obs', RAF(p1_site='u', ERK=None, state='I', MEK=None))
Observable('RAF_9_obs', RAF(p1_site='u', ERK=None, state='I', MEK=ANY))
Observable('RAF_10_obs', RAF(p1_site='u', ERK=None, state='A', MEK=None))
Observable('RAF_11_obs', RAF(p1_site='u', ERK=None, state='A', MEK=ANY))
Observable('RAF_12_obs', RAF(p1_site='u', ERK=ANY, state='I', MEK=None))
Observable('RAF_13_obs', RAF(p1_site='u', ERK=ANY, state='I', MEK=ANY))
Observable('RAF_14_obs', RAF(p1_site='u', ERK=ANY, state='A', MEK=None))
Observable('RAF_15_obs', RAF(p1_site='u', ERK=ANY, state='A', MEK=ANY))
Observable('TGFa_0_obs', TGFa(EGFR=None))
Observable('TGFa_1_obs', TGFa(EGFR=ANY))
Observable('IGF1R_0_obs', IGF1R(state='A', IGF1=None))
Observable('IGF1R_1_obs', IGF1R(state='A', IGF1=ANY))
Observable('IGF1R_2_obs', IGF1R(state='I', IGF1=None))
Observable('IGF1R_3_obs', IGF1R(state='I', IGF1=ANY))
Observable('IGF1_0_obs', IGF1(IGF1R=None))
Observable('IGF1_1_obs', IGF1(IGF1R=ANY))
Observable('PI3K_0_obs', PI3K(state='I', AKT=None))
Observable('PI3K_1_obs', PI3K(state='I', AKT=ANY))
Observable('PI3K_2_obs', PI3K(state='A', AKT=None))
Observable('PI3K_3_obs', PI3K(state='A', AKT=ANY))
Observable('p70S6K_0_obs', p70S6K(p1_site='p', ERK=None, AKT=None))
Observable('p70S6K_1_obs', p70S6K(p1_site='p', ERK=None, AKT=ANY))
Observable('p70S6K_2_obs', p70S6K(p1_site='p', ERK=ANY, AKT=None))
Observable('p70S6K_3_obs', p70S6K(p1_site='p', ERK=ANY, AKT=ANY))
Observable('p70S6K_4_obs', p70S6K(p1_site='u', ERK=None, AKT=None))
Observable('p70S6K_5_obs', p70S6K(p1_site='u', ERK=None, AKT=ANY))
Observable('p70S6K_6_obs', p70S6K(p1_site='u', ERK=ANY, AKT=None))
Observable('p70S6K_7_obs', p70S6K(p1_site='u', ERK=ANY, AKT=ANY))
Observable('EGFR_0_obs', EGFR(p1_site='p', state='A', ERK=None, TGFa=None))
Observable('EGFR_1_obs', EGFR(p1_site='p', state='A', ERK=None, TGFa=ANY))
Observable('EGFR_2_obs', EGFR(p1_site='p', state='A', ERK=ANY, TGFa=None))
Observable('EGFR_3_obs', EGFR(p1_site='p', state='A', ERK=ANY, TGFa=ANY))
Observable('EGFR_4_obs', EGFR(p1_site='p', state='I', ERK=None, TGFa=None))
Observable('EGFR_5_obs', EGFR(p1_site='p', state='I', ERK=None, TGFa=ANY))
Observable('EGFR_6_obs', EGFR(p1_site='p', state='I', ERK=ANY, TGFa=None))
Observable('EGFR_7_obs', EGFR(p1_site='p', state='I', ERK=ANY, TGFa=ANY))
Observable('EGFR_8_obs', EGFR(p1_site='u', state='A', ERK=None, TGFa=None))
Observable('EGFR_9_obs', EGFR(p1_site='u', state='A', ERK=None, TGFa=ANY))
Observable('EGFR_10_obs', EGFR(p1_site='u', state='A', ERK=ANY, TGFa=None))
Observable('EGFR_11_obs', EGFR(p1_site='u', state='A', ERK=ANY, TGFa=ANY))
Observable('EGFR_12_obs', EGFR(p1_site='u', state='I', ERK=None, TGFa=None))
Observable('EGFR_13_obs', EGFR(p1_site='u', state='I', ERK=None, TGFa=ANY))
Observable('EGFR_14_obs', EGFR(p1_site='u', state='I', ERK=ANY, TGFa=None))
Observable('EGFR_15_obs', EGFR(p1_site='u', state='I', ERK=ANY, TGFa=ANY))
Observable('IRS1_0_obs', IRS1(p1_site='p', ERK=None, AKT=None))
Observable('IRS1_1_obs', IRS1(p1_site='p', ERK=None, AKT=ANY))
Observable('IRS1_2_obs', IRS1(p1_site='p', ERK=ANY, AKT=None))
Observable('IRS1_3_obs', IRS1(p1_site='p', ERK=ANY, AKT=ANY))
Observable('IRS1_4_obs', IRS1(p1_site='u', ERK=None, AKT=None))
Observable('IRS1_5_obs', IRS1(p1_site='u', ERK=None, AKT=ANY))
Observable('IRS1_6_obs', IRS1(p1_site='u', ERK=ANY, AKT=None))
Observable('IRS1_7_obs', IRS1(p1_site='u', ERK=ANY, AKT=ANY))
Observable('MEK_0_obs', MEK(p1_site='p', p2_site='p', A_kinase_1='None', A_kinase_2='None', ERK=None))
Observable('MEK_1_obs', MEK(p1_site='p', p2_site='p', A_kinase_1='None', A_kinase_2='None', ERK=ANY))
Observable('MEK_2_obs', MEK(p1_site='p', p2_site='p', A_kinase_1='None', A_kinase_2='1', ERK=None))
Observable('MEK_3_obs', MEK(p1_site='p', p2_site='p', A_kinase_1='None', A_kinase_2='1', ERK=ANY))
Observable('MEK_4_obs', MEK(p1_site='p', p2_site='p', A_kinase_1='1', A_kinase_2='None', ERK=None))
Observable('MEK_5_obs', MEK(p1_site='p', p2_site='p', A_kinase_1='1', A_kinase_2='None', ERK=ANY))
Observable('MEK_6_obs', MEK(p1_site='p', p2_site='p', A_kinase_1='1', A_kinase_2='1', ERK=None))
Observable('MEK_7_obs', MEK(p1_site='p', p2_site='p', A_kinase_1='1', A_kinase_2='1', ERK=ANY))
Observable('MEK_8_obs', MEK(p1_site='p', p2_site='u', A_kinase_1='None', A_kinase_2='None', ERK=None))
Observable('MEK_9_obs', MEK(p1_site='p', p2_site='u', A_kinase_1='None', A_kinase_2='None', ERK=ANY))
Observable('MEK_10_obs', MEK(p1_site='p', p2_site='u', A_kinase_1='None', A_kinase_2='1', ERK=None))
Observable('MEK_11_obs', MEK(p1_site='p', p2_site='u', A_kinase_1='None', A_kinase_2='1', ERK=ANY))
Observable('MEK_12_obs', MEK(p1_site='p', p2_site='u', A_kinase_1='1', A_kinase_2='None', ERK=None))
Observable('MEK_13_obs', MEK(p1_site='p', p2_site='u', A_kinase_1='1', A_kinase_2='None', ERK=ANY))
Observable('MEK_14_obs', MEK(p1_site='p', p2_site='u', A_kinase_1='1', A_kinase_2='1', ERK=None))
Observable('MEK_15_obs', MEK(p1_site='p', p2_site='u', A_kinase_1='1', A_kinase_2='1', ERK=ANY))
Observable('MEK_16_obs', MEK(p1_site='u', p2_site='p', A_kinase_1='None', A_kinase_2='None', ERK=None))
Observable('MEK_17_obs', MEK(p1_site='u', p2_site='p', A_kinase_1='None', A_kinase_2='None', ERK=ANY))
Observable('MEK_18_obs', MEK(p1_site='u', p2_site='p', A_kinase_1='None', A_kinase_2='1', ERK=None))
Observable('MEK_19_obs', MEK(p1_site='u', p2_site='p', A_kinase_1='None', A_kinase_2='1', ERK=ANY))
Observable('MEK_20_obs', MEK(p1_site='u', p2_site='p', A_kinase_1='1', A_kinase_2='None', ERK=None))
Observable('MEK_21_obs', MEK(p1_site='u', p2_site='p', A_kinase_1='1', A_kinase_2='None', ERK=ANY))
Observable('MEK_22_obs', MEK(p1_site='u', p2_site='p', A_kinase_1='1', A_kinase_2='1', ERK=None))
Observable('MEK_23_obs', MEK(p1_site='u', p2_site='p', A_kinase_1='1', A_kinase_2='1', ERK=ANY))
Observable('MEK_24_obs', MEK(p1_site='u', p2_site='u', A_kinase_1='None', A_kinase_2='None', ERK=None))
Observable('MEK_25_obs', MEK(p1_site='u', p2_site='u', A_kinase_1='None', A_kinase_2='None', ERK=ANY))
Observable('MEK_26_obs', MEK(p1_site='u', p2_site='u', A_kinase_1='None', A_kinase_2='1', ERK=None))
Observable('MEK_27_obs', MEK(p1_site='u', p2_site='u', A_kinase_1='None', A_kinase_2='1', ERK=ANY))
Observable('MEK_28_obs', MEK(p1_site='u', p2_site='u', A_kinase_1='1', A_kinase_2='None', ERK=None))
Observable('MEK_29_obs', MEK(p1_site='u', p2_site='u', A_kinase_1='1', A_kinase_2='None', ERK=ANY))
Observable('MEK_30_obs', MEK(p1_site='u', p2_site='u', A_kinase_1='1', A_kinase_2='1', ERK=None))
Observable('MEK_31_obs', MEK(p1_site='u', p2_site='u', A_kinase_1='1', A_kinase_2='1', ERK=ANY))
Observable('AKT_0_obs', AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=None, GSK3=None))
Observable('AKT_1_obs', AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=None, GSK3=ANY))
Observable('AKT_2_obs', AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=ANY, GSK3=None))
Observable('AKT_3_obs', AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=ANY, GSK3=ANY))
Observable('AKT_4_obs', AKT(p1_site='p', p70S6K=None, IRS1=ANY, PI3K=None, GSK3=None))
Observable('AKT_5_obs', AKT(p1_site='p', p70S6K=None, IRS1=ANY, PI3K=None, GSK3=ANY))
Observable('AKT_6_obs', AKT(p1_site='p', p70S6K=None, IRS1=ANY, PI3K=ANY, GSK3=None))
Observable('AKT_7_obs', AKT(p1_site='p', p70S6K=None, IRS1=ANY, PI3K=ANY, GSK3=ANY))
Observable('AKT_8_obs', AKT(p1_site='p', p70S6K=ANY, IRS1=None, PI3K=None, GSK3=None))
Observable('AKT_9_obs', AKT(p1_site='p', p70S6K=ANY, IRS1=None, PI3K=None, GSK3=ANY))
Observable('AKT_10_obs', AKT(p1_site='p', p70S6K=ANY, IRS1=None, PI3K=ANY, GSK3=None))
Observable('AKT_11_obs', AKT(p1_site='p', p70S6K=ANY, IRS1=None, PI3K=ANY, GSK3=ANY))
Observable('AKT_12_obs', AKT(p1_site='p', p70S6K=ANY, IRS1=ANY, PI3K=None, GSK3=None))
Observable('AKT_13_obs', AKT(p1_site='p', p70S6K=ANY, IRS1=ANY, PI3K=None, GSK3=ANY))
Observable('AKT_14_obs', AKT(p1_site='p', p70S6K=ANY, IRS1=ANY, PI3K=ANY, GSK3=None))
Observable('AKT_15_obs', AKT(p1_site='p', p70S6K=ANY, IRS1=ANY, PI3K=ANY, GSK3=ANY))
Observable('AKT_16_obs', AKT(p1_site='u', p70S6K=None, IRS1=None, PI3K=None, GSK3=None))
Observable('AKT_17_obs', AKT(p1_site='u', p70S6K=None, IRS1=None, PI3K=None, GSK3=ANY))
Observable('AKT_18_obs', AKT(p1_site='u', p70S6K=None, IRS1=None, PI3K=ANY, GSK3=None))
Observable('AKT_19_obs', AKT(p1_site='u', p70S6K=None, IRS1=None, PI3K=ANY, GSK3=ANY))
Observable('AKT_20_obs', AKT(p1_site='u', p70S6K=None, IRS1=ANY, PI3K=None, GSK3=None))
Observable('AKT_21_obs', AKT(p1_site='u', p70S6K=None, IRS1=ANY, PI3K=None, GSK3=ANY))
Observable('AKT_22_obs', AKT(p1_site='u', p70S6K=None, IRS1=ANY, PI3K=ANY, GSK3=None))
Observable('AKT_23_obs', AKT(p1_site='u', p70S6K=None, IRS1=ANY, PI3K=ANY, GSK3=ANY))
Observable('AKT_24_obs', AKT(p1_site='u', p70S6K=ANY, IRS1=None, PI3K=None, GSK3=None))
Observable('AKT_25_obs', AKT(p1_site='u', p70S6K=ANY, IRS1=None, PI3K=None, GSK3=ANY))
Observable('AKT_26_obs', AKT(p1_site='u', p70S6K=ANY, IRS1=None, PI3K=ANY, GSK3=None))
Observable('AKT_27_obs', AKT(p1_site='u', p70S6K=ANY, IRS1=None, PI3K=ANY, GSK3=ANY))
Observable('AKT_28_obs', AKT(p1_site='u', p70S6K=ANY, IRS1=ANY, PI3K=None, GSK3=None))
Observable('AKT_29_obs', AKT(p1_site='u', p70S6K=ANY, IRS1=ANY, PI3K=None, GSK3=ANY))
Observable('AKT_30_obs', AKT(p1_site='u', p70S6K=ANY, IRS1=ANY, PI3K=ANY, GSK3=None))
Observable('AKT_31_obs', AKT(p1_site='u', p70S6K=ANY, IRS1=ANY, PI3K=ANY, GSK3=ANY))
Observable('GSK3_0_obs', GSK3(p1_site='p', ERK=None, AKT=None))
Observable('GSK3_1_obs', GSK3(p1_site='p', ERK=None, AKT=ANY))
Observable('GSK3_2_obs', GSK3(p1_site='p', ERK=ANY, AKT=None))
Observable('GSK3_3_obs', GSK3(p1_site='p', ERK=ANY, AKT=ANY))
Observable('GSK3_4_obs', GSK3(p1_site='u', ERK=None, AKT=None))
Observable('GSK3_5_obs', GSK3(p1_site='u', ERK=None, AKT=ANY))
Observable('GSK3_6_obs', GSK3(p1_site='u', ERK=ANY, AKT=None))
Observable('GSK3_7_obs', GSK3(p1_site='u', ERK=ANY, AKT=ANY))
Observable('ERK_0_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_1_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_2_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_3_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_4_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_5_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_6_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_7_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_8_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_9_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_10_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_11_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_12_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_13_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_14_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_15_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_16_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_17_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_18_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_19_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_20_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_21_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_22_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_23_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_24_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_25_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_26_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_27_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_28_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_29_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_30_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_31_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_32_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_33_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_34_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_35_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_36_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_37_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_38_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_39_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_40_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_41_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_42_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_43_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_44_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_45_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_46_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_47_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_48_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_49_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_50_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_51_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_52_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_53_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_54_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_55_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_56_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_57_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_58_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_59_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_60_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_61_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_62_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_63_obs', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_64_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_65_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_66_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_67_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_68_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_69_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_70_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_71_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_72_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_73_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_74_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_75_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_76_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_77_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_78_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_79_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_80_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_81_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_82_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_83_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_84_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_85_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_86_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_87_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_88_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_89_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_90_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_91_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_92_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_93_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_94_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_95_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_96_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_97_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_98_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_99_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_100_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_101_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_102_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_103_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_104_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_105_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_106_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_107_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_108_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_109_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_110_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_111_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_112_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_113_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_114_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_115_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_116_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_117_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_118_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_119_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_120_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_121_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_122_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_123_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_124_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_125_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_126_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_127_obs', ERK(p1_site='p', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_128_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_129_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_130_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_131_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_132_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_133_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_134_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_135_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_136_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_137_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_138_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_139_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_140_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_141_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_142_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_143_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_144_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_145_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_146_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_147_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_148_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_149_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_150_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_151_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_152_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_153_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_154_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_155_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_156_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_157_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_158_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_159_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_160_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_161_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_162_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_163_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_164_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_165_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_166_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_167_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_168_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_169_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_170_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_171_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_172_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_173_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_174_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_175_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_176_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_177_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_178_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_179_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_180_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_181_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_182_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_183_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_184_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_185_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_186_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_187_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_188_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_189_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_190_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_191_obs', ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_192_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_193_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_194_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_195_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_196_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_197_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_198_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_199_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_200_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_201_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_202_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_203_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_204_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_205_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_206_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_207_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_208_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_209_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_210_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_211_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_212_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_213_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_214_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_215_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_216_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_217_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_218_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_219_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_220_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_221_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_222_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_223_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_224_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_225_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_226_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_227_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_228_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_229_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_230_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_231_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_232_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_233_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_234_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_235_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_236_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_237_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_238_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_239_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_240_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_241_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_242_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_243_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_244_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_245_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_246_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_247_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_248_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_249_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_250_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_251_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_252_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_253_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_254_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_255_obs', ERK(p1_site='p', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_256_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_257_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_258_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_259_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_260_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_261_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_262_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_263_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_264_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_265_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_266_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_267_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_268_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_269_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_270_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_271_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_272_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_273_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_274_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_275_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_276_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_277_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_278_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_279_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_280_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_281_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_282_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_283_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_284_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_285_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_286_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_287_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_288_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_289_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_290_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_291_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_292_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_293_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_294_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_295_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_296_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_297_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_298_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_299_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_300_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_301_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_302_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_303_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_304_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_305_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_306_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_307_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_308_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_309_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_310_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_311_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_312_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_313_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_314_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_315_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_316_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_317_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_318_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_319_obs', ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_320_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_321_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_322_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_323_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_324_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_325_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_326_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_327_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_328_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_329_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_330_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_331_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_332_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_333_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_334_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_335_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_336_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_337_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_338_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_339_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_340_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_341_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_342_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_343_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_344_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_345_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_346_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_347_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_348_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_349_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_350_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_351_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_352_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_353_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_354_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_355_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_356_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_357_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_358_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_359_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_360_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_361_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_362_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_363_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_364_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_365_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_366_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_367_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_368_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_369_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_370_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_371_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_372_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_373_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_374_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_375_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_376_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_377_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_378_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_379_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_380_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_381_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_382_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_383_obs', ERK(p1_site='u', p2_site='p', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_384_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_385_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_386_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_387_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_388_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_389_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_390_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_391_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_392_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_393_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_394_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_395_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_396_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_397_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_398_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_399_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_400_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_401_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_402_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_403_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_404_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_405_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_406_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_407_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_408_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_409_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_410_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_411_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_412_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_413_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_414_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_415_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_416_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_417_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_418_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_419_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_420_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_421_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_422_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_423_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_424_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_425_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_426_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_427_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_428_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_429_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_430_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_431_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_432_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_433_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_434_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_435_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_436_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_437_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_438_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_439_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_440_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_441_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_442_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_443_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_444_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_445_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_446_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_447_obs', ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_448_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_449_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_450_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_451_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_452_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_453_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_454_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_455_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_456_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_457_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_458_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_459_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_460_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_461_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_462_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_463_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_464_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_465_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_466_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_467_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_468_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_469_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_470_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_471_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_472_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_473_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_474_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_475_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_476_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_477_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_478_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_479_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=None, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_480_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_481_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_482_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_483_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_484_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_485_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_486_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_487_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_488_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_489_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_490_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_491_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_492_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_493_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_494_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_495_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=None, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_496_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_497_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_498_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_499_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_500_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_501_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_502_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_503_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=None, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_504_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=None))
Observable('ERK_505_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=None, MEK_2=ANY))
Observable('ERK_506_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=None))
Observable('ERK_507_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=None, MEK_1=ANY, MEK_2=ANY))
Observable('ERK_508_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=None))
Observable('ERK_509_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=None, MEK_2=ANY))
Observable('ERK_510_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=None))
Observable('ERK_511_obs', ERK(p1_site='u', p2_site='u', RAF=ANY, p70S6K=ANY, EGFR=ANY, IRS1=ANY, GSK3=ANY, MEK_1=ANY, MEK_2=ANY))

Rule('RAF_p1_auto_dephosphorylation_0', RAF(p1_site='p', ERK=None, MEK=None) >> RAF(p1_site='u', ERK=None, MEK=None), RAF_p1_auto_dephosphorylation_0_1kc)
Rule('p70S6K_p1_auto_dephosphorylation_0', p70S6K(p1_site='p', ERK=None, AKT=None) >> p70S6K(p1_site='u', ERK=None, AKT=None), p70S6K_p1_auto_dephosphorylation_0_1kc)
Rule('EGFR_p1_auto_dephosphorylation_0', EGFR(p1_site='p', ERK=None, TGFa=None) >> EGFR(p1_site='u', ERK=None, TGFa=None), EGFR_p1_auto_dephosphorylation_0_1kc)
Rule('IRS1_p1_auto_dephosphorylation_0', IRS1(p1_site='p', ERK=None, AKT=None) >> IRS1(p1_site='u', ERK=None, AKT=None), IRS1_p1_auto_dephosphorylation_0_1kc)
Rule('MEK_p2_auto_dephosphorylation_0', MEK(p1_site='p', ERK=None) >> MEK(p1_site='u', ERK=None), MEK_p2_auto_dephosphorylation_0_1kc)
Rule('MEK_p2_auto_dephosphorylation_1', MEK(p2_site='p', ERK=None) >> MEK(p2_site='u', ERK=None), MEK_p2_auto_dephosphorylation_1_1kc)
Rule('AKT_p1_auto_dephosphorylation_0', AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=None, GSK3=None) >> AKT(p1_site='u', p70S6K=None, IRS1=None, PI3K=None, GSK3=None), AKT_p1_auto_dephosphorylation_0_1kc)
Rule('GSK3_p1_auto_dephosphorylation_0', GSK3(p1_site='p', ERK=None, AKT=None) >> GSK3(p1_site='u', ERK=None, AKT=None), GSK3_p1_auto_dephosphorylation_0_1kc)
Rule('ERK_p2_auto_dephosphorylation_0', ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None) >> ERK(p1_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None), ERK_p2_auto_dephosphorylation_0_1kc)
Rule('ERK_p2_auto_dephosphorylation_1', ERK(p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None) >> ERK(p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None), ERK_p2_auto_dephosphorylation_1_1kc)
Rule('ERK_p2_p1_phosphorylation_RAF_0', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None) + RAF(p1_site='u', ERK=None, MEK=None) <> ERK(p1_site='p', p2_site='p', RAF=1, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None) % RAF(p1_site='u', ERK=1, MEK=None), ERK_p2_p1_phosphorylation_RAF_0_2kf, ERK_p2_p1_phosphorylation_RAF_0_1kr)
Rule('ERK_p2_p1_phosphorylation_RAF_1', ERK(p1_site='p', p2_site='p', RAF=1, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None) % RAF(p1_site='u', ERK=1, MEK=None) >> ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None) + RAF(p1_site='p', ERK=None, MEK=None), ERK_p2_p1_phosphorylation_RAF_1_1kc)
Rule('EGFR_A_u_activation_RAF_0', EGFR(p1_site='u', state='A') + RAF(state='I') >> EGFR(p1_site='u', state='A') + RAF(state='A'), EGFR_A_u_activation_RAF_0_2kc)
Rule('IGF1R_A_activation_RAF_0', IGF1R(state='A') + RAF(state='I') >> IGF1R(state='A') + RAF(state='A'), IGF1R_A_activation_RAF_0_2kc)
Rule('IGF1_ligand_receptor_binding_IGF1R_0', IGF1(IGF1R=None) + IGF1R(state='I', IGF1=None) <> IGF1(IGF1R=1) % IGF1R(state='A', IGF1=1), IGF1_ligand_receptor_binding_IGF1R_0_2kf, IGF1_ligand_receptor_binding_IGF1R_0_1kr)
Rule('EGFR_A_u_activation_PI3K_0', EGFR(p1_site='u', state='A') + PI3K(state='I') >> EGFR(p1_site='u', state='A') + PI3K(state='A'), EGFR_A_u_activation_PI3K_0_2kc)
Rule('IGF1R_A_activation_PI3K_0', IGF1R(state='A') + PI3K(state='I') >> IGF1R(state='A') + PI3K(state='A'), IGF1R_A_activation_PI3K_0_2kc)
Rule('ERK_p2_p1_phosphorylation_p70S6K_0', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None) + p70S6K(p1_site='u', ERK=None, AKT=None) <> ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=1, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None) % p70S6K(p1_site='u', ERK=1, AKT=None), ERK_p2_p1_phosphorylation_p70S6K_0_2kf, ERK_p2_p1_phosphorylation_p70S6K_0_1kr)
Rule('ERK_p2_p1_phosphorylation_p70S6K_1', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=1, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None) % p70S6K(p1_site='u', ERK=1, AKT=None) >> ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None) + p70S6K(p1_site='p', ERK=None, AKT=None), ERK_p2_p1_phosphorylation_p70S6K_1_1kc)
Rule('AKT_p1_p1_phosphorylation_p70S6K_0', AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=None, GSK3=None) + p70S6K(p1_site='u', ERK=None, AKT=None) <> AKT(p1_site='p', p70S6K=1, IRS1=None, PI3K=None, GSK3=None) % p70S6K(p1_site='u', ERK=None, AKT=1), AKT_p1_p1_phosphorylation_p70S6K_0_2kf, AKT_p1_p1_phosphorylation_p70S6K_0_1kr)
Rule('AKT_p1_p1_phosphorylation_p70S6K_1', AKT(p1_site='p', p70S6K=1, IRS1=None, PI3K=None, GSK3=None) % p70S6K(p1_site='u', ERK=None, AKT=1) >> AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=None, GSK3=None) + p70S6K(p1_site='p', ERK=None, AKT=None), AKT_p1_p1_phosphorylation_p70S6K_1_1kc)
Rule('ERK_p2_p1_phosphorylation_EGFR_0', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None) + EGFR(p1_site='u', ERK=None, TGFa=None) <> ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=1, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None) % EGFR(p1_site='u', ERK=1, TGFa=None), ERK_p2_p1_phosphorylation_EGFR_0_2kf, ERK_p2_p1_phosphorylation_EGFR_0_1kr)
Rule('ERK_p2_p1_phosphorylation_EGFR_1', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=1, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None) % EGFR(p1_site='u', ERK=1, TGFa=None) >> ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None) + EGFR(p1_site='p', ERK=None, TGFa=None), ERK_p2_p1_phosphorylation_EGFR_1_1kc)
Rule('TGFa_ligand_receptor_binding_EGFR_0', TGFa(EGFR=None) + EGFR(state='I', ERK=None, TGFa=None) <> TGFa(EGFR=1) % EGFR(state='A', ERK=None, TGFa=1), TGFa_ligand_receptor_binding_EGFR_0_2kf, TGFa_ligand_receptor_binding_EGFR_0_1kr)
Rule('ERK_p2_p1_phosphorylation_IRS1_0', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None) + IRS1(p1_site='u', ERK=None, AKT=None) <> ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=1, GSK3=None, MEK_1=None, MEK_2=None) % IRS1(p1_site='u', ERK=1, AKT=None), ERK_p2_p1_phosphorylation_IRS1_0_2kf, ERK_p2_p1_phosphorylation_IRS1_0_1kr)
Rule('ERK_p2_p1_phosphorylation_IRS1_1', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=1, GSK3=None, MEK_1=None, MEK_2=None) % IRS1(p1_site='u', ERK=1, AKT=None) >> ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None) + IRS1(p1_site='p', ERK=None, AKT=None), ERK_p2_p1_phosphorylation_IRS1_1_1kc)
Rule('AKT_p1_p1_phosphorylation_IRS1_0', AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=None, GSK3=None) + IRS1(p1_site='u', ERK=None, AKT=None) <> AKT(p1_site='p', p70S6K=None, IRS1=1, PI3K=None, GSK3=None) % IRS1(p1_site='u', ERK=None, AKT=1), AKT_p1_p1_phosphorylation_IRS1_0_2kf, AKT_p1_p1_phosphorylation_IRS1_0_1kr)
Rule('AKT_p1_p1_phosphorylation_IRS1_1', AKT(p1_site='p', p70S6K=None, IRS1=1, PI3K=None, GSK3=None) % IRS1(p1_site='u', ERK=None, AKT=1) >> AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=None, GSK3=None) + IRS1(p1_site='p', ERK=None, AKT=None), AKT_p1_p1_phosphorylation_IRS1_1_1kc)
Rule('RAF_A_u_p2_phosphorylation_MEK_0', RAF(p1_site='u', ERK=None, state='A', MEK=None) + MEK(p1_site='u', A_kinase_1=None, ERK=None) <> RAF(p1_site='u', ERK=None, state='A', MEK=1) % MEK(p1_site='u', A_kinase_1='1', ERK=None), RAF_A_u_p2_phosphorylation_MEK_0_2kf, RAF_A_u_p2_phosphorylation_MEK_0_1kr)
Rule('RAF_A_u_p2_phosphorylation_MEK_1', RAF(p1_site='u', ERK=None, state='A', MEK=1) % MEK(p1_site='u', A_kinase_1='1', ERK=None) >> RAF(p1_site='u', ERK=None, state='A', MEK=None) + MEK(p1_site='p', A_kinase_1=None, ERK=None), RAF_A_u_p2_phosphorylation_MEK_1_1kc)
Rule('RAF_A_u_p2_phosphorylation_MEK_2', RAF(p1_site='u', ERK=None, state='A', MEK=None) + MEK(p2_site='u', A_kinase_2=None, ERK=None) <> RAF(p1_site='u', ERK=None, state='A', MEK=1) % MEK(p2_site='u', A_kinase_2='1', ERK=None), RAF_A_u_p2_phosphorylation_MEK_2_2kf, RAF_A_u_p2_phosphorylation_MEK_2_1kr)
Rule('RAF_A_u_p2_phosphorylation_MEK_3', RAF(p1_site='u', ERK=None, state='A', MEK=1) % MEK(p2_site='u', A_kinase_2='1', ERK=None) >> RAF(p1_site='u', ERK=None, state='A', MEK=None) + MEK(p2_site='p', A_kinase_2=None, ERK=None), RAF_A_u_p2_phosphorylation_MEK_3_1kc)
Rule('PI3K_A_p1_phosphorylation_AKT_0', PI3K(state='A', AKT=None) + AKT(p1_site='u', p70S6K=None, IRS1=None, PI3K=None, GSK3=None) <> PI3K(state='A', AKT=1) % AKT(p1_site='u', p70S6K=None, IRS1=None, PI3K=1, GSK3=None), PI3K_A_p1_phosphorylation_AKT_0_2kf, PI3K_A_p1_phosphorylation_AKT_0_1kr)
Rule('PI3K_A_p1_phosphorylation_AKT_1', PI3K(state='A', AKT=1) % AKT(p1_site='u', p70S6K=None, IRS1=None, PI3K=1, GSK3=None) >> PI3K(state='A', AKT=None) + AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=None, GSK3=None), PI3K_A_p1_phosphorylation_AKT_1_1kc)
Rule('ERK_p2_p1_phosphorylation_GSK3_0', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None) + GSK3(p1_site='u', ERK=None, AKT=None) <> ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=1, MEK_1=None, MEK_2=None) % GSK3(p1_site='u', ERK=1, AKT=None), ERK_p2_p1_phosphorylation_GSK3_0_2kf, ERK_p2_p1_phosphorylation_GSK3_0_1kr)
Rule('ERK_p2_p1_phosphorylation_GSK3_1', ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=1, MEK_1=None, MEK_2=None) % GSK3(p1_site='u', ERK=1, AKT=None) >> ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None) + GSK3(p1_site='p', ERK=None, AKT=None), ERK_p2_p1_phosphorylation_GSK3_1_1kc)
Rule('AKT_p1_p1_phosphorylation_GSK3_0', AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=None, GSK3=None) + GSK3(p1_site='u', ERK=None, AKT=None) <> AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=None, GSK3=1) % GSK3(p1_site='u', ERK=None, AKT=1), AKT_p1_p1_phosphorylation_GSK3_0_2kf, AKT_p1_p1_phosphorylation_GSK3_0_1kr)
Rule('AKT_p1_p1_phosphorylation_GSK3_1', AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=None, GSK3=1) % GSK3(p1_site='u', ERK=None, AKT=1) >> AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=None, GSK3=None) + GSK3(p1_site='p', ERK=None, AKT=None), AKT_p1_p1_phosphorylation_GSK3_1_1kc)
Rule('MEK_p2_p2_phosphorylation_ERK_0', MEK(p1_site='p', p2_site='p', ERK=None) + ERK(p1_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None) <> MEK(p1_site='p', p2_site='p', ERK=1) % ERK(p1_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=1, MEK_2=None), MEK_p2_p2_phosphorylation_ERK_0_2kf, MEK_p2_p2_phosphorylation_ERK_0_1kr)
Rule('MEK_p2_p2_phosphorylation_ERK_1', MEK(p1_site='p', p2_site='p', ERK=1) % ERK(p1_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=1, MEK_2=None) >> MEK(p1_site='p', p2_site='p', ERK=None) + ERK(p1_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None), MEK_p2_p2_phosphorylation_ERK_1_1kc)
Rule('MEK_p2_p2_phosphorylation_ERK_2', MEK(p1_site='p', p2_site='p', ERK=None) + ERK(p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None) <> MEK(p1_site='p', p2_site='p', ERK=1) % ERK(p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=1), MEK_p2_p2_phosphorylation_ERK_2_2kf, MEK_p2_p2_phosphorylation_ERK_2_1kr)
Rule('MEK_p2_p2_phosphorylation_ERK_3', MEK(p1_site='p', p2_site='p', ERK=1) % ERK(p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=1) >> MEK(p1_site='p', p2_site='p', ERK=None) + ERK(p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None), MEK_p2_p2_phosphorylation_ERK_3_1kc)

Initial(RAF(p1_site='p', ERK=None, state='I', MEK=None), RAF_0_0)
Initial(RAF(p1_site='p', ERK=None, state='A', MEK=None), RAF_1_0)
Initial(RAF(p1_site='u', ERK=None, state='I', MEK=None), RAF_2_0)
Initial(RAF(p1_site='u', ERK=None, state='A', MEK=None), RAF_3_0)
Initial(TGFa(EGFR=None), TGFa_0_0)
Initial(IGF1R(state='A', IGF1=None), IGF1R_0_0)
Initial(IGF1R(state='I', IGF1=None), IGF1R_1_0)
Initial(IGF1(IGF1R=None), IGF1_0_0)
Initial(PI3K(state='I', AKT=None), PI3K_0_0)
Initial(PI3K(state='A', AKT=None), PI3K_1_0)
Initial(p70S6K(p1_site='p', ERK=None, AKT=None), p70S6K_0_0)
Initial(p70S6K(p1_site='u', ERK=None, AKT=None), p70S6K_1_0)
Initial(EGFR(p1_site='p', state='A', ERK=None, TGFa=None), EGFR_0_0)
Initial(EGFR(p1_site='p', state='I', ERK=None, TGFa=None), EGFR_1_0)
Initial(EGFR(p1_site='u', state='A', ERK=None, TGFa=None), EGFR_2_0)
Initial(EGFR(p1_site='u', state='I', ERK=None, TGFa=None), EGFR_3_0)
Initial(IRS1(p1_site='p', ERK=None, AKT=None), IRS1_0_0)
Initial(IRS1(p1_site='u', ERK=None, AKT=None), IRS1_1_0)
Initial(MEK(p1_site='p', p2_site='p', A_kinase_1='None', A_kinase_2='None', ERK=None), MEK_0_0)
Initial(MEK(p1_site='p', p2_site='p', A_kinase_1='None', A_kinase_2='1', ERK=None), MEK_1_0)
Initial(MEK(p1_site='p', p2_site='p', A_kinase_1='1', A_kinase_2='None', ERK=None), MEK_2_0)
Initial(MEK(p1_site='p', p2_site='p', A_kinase_1='1', A_kinase_2='1', ERK=None), MEK_3_0)
Initial(MEK(p1_site='p', p2_site='u', A_kinase_1='None', A_kinase_2='None', ERK=None), MEK_4_0)
Initial(MEK(p1_site='p', p2_site='u', A_kinase_1='None', A_kinase_2='1', ERK=None), MEK_5_0)
Initial(MEK(p1_site='p', p2_site='u', A_kinase_1='1', A_kinase_2='None', ERK=None), MEK_6_0)
Initial(MEK(p1_site='p', p2_site='u', A_kinase_1='1', A_kinase_2='1', ERK=None), MEK_7_0)
Initial(MEK(p1_site='u', p2_site='p', A_kinase_1='None', A_kinase_2='None', ERK=None), MEK_8_0)
Initial(MEK(p1_site='u', p2_site='p', A_kinase_1='None', A_kinase_2='1', ERK=None), MEK_9_0)
Initial(MEK(p1_site='u', p2_site='p', A_kinase_1='1', A_kinase_2='None', ERK=None), MEK_10_0)
Initial(MEK(p1_site='u', p2_site='p', A_kinase_1='1', A_kinase_2='1', ERK=None), MEK_11_0)
Initial(MEK(p1_site='u', p2_site='u', A_kinase_1='None', A_kinase_2='None', ERK=None), MEK_12_0)
Initial(MEK(p1_site='u', p2_site='u', A_kinase_1='None', A_kinase_2='1', ERK=None), MEK_13_0)
Initial(MEK(p1_site='u', p2_site='u', A_kinase_1='1', A_kinase_2='None', ERK=None), MEK_14_0)
Initial(MEK(p1_site='u', p2_site='u', A_kinase_1='1', A_kinase_2='1', ERK=None), MEK_15_0)
Initial(AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=None, GSK3=None), AKT_0_0)
Initial(AKT(p1_site='u', p70S6K=None, IRS1=None, PI3K=None, GSK3=None), AKT_1_0)
Initial(GSK3(p1_site='p', ERK=None, AKT=None), GSK3_0_0)
Initial(GSK3(p1_site='u', ERK=None, AKT=None), GSK3_1_0)
Initial(ERK(p1_site='p', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None), ERK_0_0)
Initial(ERK(p1_site='p', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None), ERK_1_0)
Initial(ERK(p1_site='u', p2_site='p', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None), ERK_2_0)
Initial(ERK(p1_site='u', p2_site='u', RAF=None, p70S6K=None, EGFR=None, IRS1=None, GSK3=None, MEK_1=None, MEK_2=None), ERK_3_0)

